package net.bestia.worldgen.history

import net.bestia.worldgen.core.Faction
import net.bestia.worldgen.core.Params
import net.bestia.worldgen.core.ParamsDigest
import net.bestia.worldgen.core.ParamsText

/**
 * How much of a world's history each of the three Orders shaped, as relative weights.
 *
 * ### All zero means the Orders are absent, and that is the default
 *
 * A world whose weights are all zero has no Order in its chronicle whatsoever: no civilisation swears to one,
 * no shrine is raised, no rendered line names one, and [net.bestia.worldgen.core.Chronicle.hasOrders] is
 * false. That is what the **first** incarnation gets, and it is the right answer rather than a degenerate one -
 * the Orders' presence in a world's deep history is the residue of a *previous* world having had a victor, so
 * on the world before any victor there is nothing to leave a residue.
 *
 * It also has a property worth stating because a test asserts it: with these weights the whole Order pass
 * returns before it draws a single keyed roll, so a world generated with them is identical to one generated by
 * the code that existed before the Orders did - event for event, id for id, sentence for sentence.
 *
 * ### Relative, not a winner plus a bonus
 *
 * These are three weights normalised at use, the same shape [net.bestia.worldgen.civ.Culture]'s habitability
 * weights take and for the same reason: only the ratios matter, so a designer can express any distribution -
 * a two-way split, a world one Order never reached - rather than only "everybody equal, except the winner".
 * [favouring] is the convenience for the case the server actually has.
 *
 * ### What they are, and are not
 *
 * A thumb on the scale. `HistorySim.swearOrders` multiplies these by what a civilisation has actually *lived
 * through* - a people whose fields the blight took leans to Eternity whatever this says, a people with a wound
 * inside their reach leans to Chaos - so a heavily weighted Order is the one a world has more of, never the
 * only one it has. A weight of zero is the exception and does mean absent: it removes that Order from the draw
 * entirely, which is how a world where only two of the three ever took hold is expressed.
 */
data class OrderInfluence(
  val chaos: Double = 0.0,
  val eternity: Double = 0.0,
  val circle: Double = 0.0
) : Params {

  init {
    require(chaos >= 0.0) { "chaos influence must not be negative, was $chaos" }
    require(eternity >= 0.0) { "eternity influence must not be negative, was $eternity" }
    require(circle >= 0.0) { "circle influence must not be negative, was $circle" }
  }

  /** Whether the Orders play no part in this world's history. See the class KDoc. */
  val isAbsent: Boolean get() = total <= 0.0

  val total: Double get() = chaos + eternity + circle

  fun weightOf(faction: Faction): Double = when (faction) {
    Faction.CHAOS -> chaos
    Faction.ETERNITY -> eternity
    Faction.CIRCLE -> circle
  }

  fun overriddenBy(source: ParamsText.ParamsSource) = copy(
    chaos = source.double("chaos", chaos),
    eternity = source.double("eternity", eternity),
    circle = source.double("circle", circle)
  )

  override fun digest() = ParamsDigest()
    .put("chaos", chaos)
    .put("eternity", eternity)
    .put("circle", circle)

  companion object {

    /** The Orders play no part. What a world with no predecessor gets. */
    val NONE = OrderInfluence()

    /** All three equally, for a world whose previous incarnation ended without a victor. */
    val BALANCED = OrderInfluence(1.0, 1.0, 1.0)

    /**
     * All three present, with [winner] weighted [bonus] higher for having won the previous world.
     *
     * The default bonus is deliberately modest: a player who knows which Order won last time should be able to
     * *notice* it in the ruins, not read it off them.
     *
     * **Measured rather than reasoned**, because the naive arithmetic is not what comes out. A 1.5 weight does
     * not give a 43/28/28 split, since the draw is also weighted by what each civilisation lived through and
     * since schisms redistribute afterwards. Across eight seeds of a 384 km world, counting every sworn
     * civilisation at the present day:
     *
     * | weights | Chaos | Eternity | Circle |
     * |---|---|---|---|
     * | 1.0 / 1.0 / 1.0 | 52% | 33% | 14% |
     * | 1.0 / **1.5** / 1.0 | 38% | **43%** | 19% |
     *
     * So favouring an Order moves it about ten points and costs its chief rival rather more - a tilt a player
     * could infer from a world's ruins over time, and nowhere near a monopoly. The Circle is the smallest under
     * every weighting, which is `factions.md`'s stated intent for it rather than an artefact.
     */
    fun favouring(winner: Faction, bonus: Double = 0.5): OrderInfluence {
      require(bonus >= 0.0) { "bonus must not be negative, was $bonus" }
      val favoured = 1.0 + bonus
      return OrderInfluence(
        chaos = if (winner == Faction.CHAOS) favoured else 1.0,
        eternity = if (winner == Faction.ETERNITY) favoured else 1.0,
        circle = if (winner == Faction.CIRCLE) favoured else 1.0
      )
    }
  }
}
