package net.bestia.worldgen.voxel

/**
 * The one version number a client that only receives chunks has to agree with the server about.
 *
 * It covers the three things such a client actually does with a chunk: decode it ([RleCodec]), name the
 * materials in it ([BlockType]), and apply the removals that arrive afterwards (`ChunkPatchCodec`). Any of
 * them changing makes payloads wrong, and none is something the client can adapt to at runtime - so there is
 * nothing to gain from telling it *which* one moved. It gets one number, and if it does not match, it is out
 * of date.
 *
 * ### Why this is hand-incremented when the server's own versions are hashes
 *
 * [net.bestia.worldgen.store.PipelineVersion] hashes stage ids and the palette because it is a *cache key*:
 * forgetting to bump it there would silently serve terrain generated by a different build, and correct-by-
 * construction is the only defensible property for something with that failure mode.
 *
 * This is not a cache key. It is a compatibility statement between two independently released artefacts, one
 * of which is not built from this source tree, so it has to be a number a human can copy - a hash would
 * change on a whitespace-insensitive palette reordering that changes nothing the client can observe, and
 * would force a client release for it.
 *
 * The forgetting-to-bump risk that leaves is caught deliberately rather than structurally:
 * `ChunkStoreTest.the block palette is pinned` fails the build when [BlockType] changes, which is the point
 * at which somebody has to come here and decide.
 */
object ChunkEngine {

  /**
   * Bump on any change to [RleCodec]'s format, to `ChunkPatchCodec`'s format, or to [BlockType]'s ids, names,
   * or `solid` flag, and change the client's `ChunkEngine.Version` in the same commit.
   *
   * `BlockType.opacity` is deliberately **not** in that list. It decides how much of a sight line a material
   * stops, which is a server-side combat question the client neither receives nor renders; bumping for it
   * would force a client release for a number no client can observe.
   *
   * `BlockType.passability` is not in that list either, for the same reason: it decides what a server-side
   * pathfinder will walk into. No client receives it and none could act on it.
   *
   * ### Back at 1, once
   *
   * This reached 4 over the branch that built the palette out - worked materials, then vegetation, then
   * graded ore - and each of those bumps was a compatibility statement made to a client that did not exist
   * yet. It was reset to 1 in the same commit as every stage version, for the same reason: the promise had
   * no counterparty. **From the first client release onwards it is append-only again**, and the discipline
   * above is what it always was. This is the last free reset it gets.
   *
   * 3 added the volcanic materials in one batch - LAVA, OBSIDIAN, and graded sulfur and pyrelith - rather than
   * one bump per feature. Four separate additions would have meant four client releases for one feature.
   *
   * 4 is the removal-only patch format: an edit that carried `(index, blockId, occupancy)` became a removal
   * carrying `(indexDelta, remainingOccupancy)`. **The first bump made for the patch codec rather than for a
   * chunk payload**, and the reason it is a bump at all rather than a note is that the two formats are
   * mutually undetectable - every byte of one is a legal varint continuation in the other, so a mismatched
   * client decodes plausible geometry instead of failing. `ChunkPatchEncoding` on the message catches it
   * per patch; this catches it at the handshake, before a single one is sent.
   */
  const val VERSION = 4
}
