package net.bestia.worldgen.voxel

/**
 * The one version number a client that only receives chunks has to agree with the server about.
 *
 * It covers the two things such a client actually does with a chunk: decode it ([RleCodec]) and name the
 * materials in it ([BlockType]). Either changing makes every payload wrong, and neither is something the
 * client can adapt to at runtime - so there is nothing to gain from telling it *which* one moved. It gets one
 * number, and if it does not match, it is out of date.
 *
 * ### Why this is hand-incremented when the server's own versions are hashes
 *
 * [net.bestia.worldgen.store.PipelineVersion] hashes stage ids and the palette because it is a *cache key*:
 * forgetting to bump it there would silently serve terrain generated by a different build, and correct-by-
 * construction is the only defensible property for something with that failure mode.
 *
 * This is not a cache key. It is a compatibility statement between two independently released artefacts, one
 * of which is not built from this source tree, so it has to be a number a human can copy - a hash would
 * change on a whitespace-insensitive palette reordering that changes nothing the client can observe, and
 * would force a client release for it.
 *
 * The forgetting-to-bump risk that leaves is caught deliberately rather than structurally:
 * `ChunkStoreTest.the block palette is pinned` fails the build when [BlockType] changes, which is the point
 * at which somebody has to come here and decide.
 */
object ChunkEngine {

  /**
   * Bump on any change to [RleCodec]'s format or to [BlockType]'s ids, names, or `solid` flag, and change the
   * client's `ChunkEngine.Version` in the same commit.
   *
   * 1 is the first value that means anything: before it the client compared the RLE version alone and had no
   * way to notice a palette it disagreed with.
   */
  const val VERSION = 1
}
