version: '3'
services:
  mysql:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bestia
      MYSQL_USER: bestia
      MYSQL_PASSWORD: bestia
      MYSQL_ROOT_PASSWORD: bestia
  cassandra:
    # https://docs.docker.com/samples/library/cassandra/
    image: cassandra:3
    restart: always
    ports:
      - 7000:7000
      - 9042:9042
  neo4j:
    # https://neo4j.com/developer/docker-run-neo4j/
    image: neo4j:4.0.4
    ports:
      - 7474:7474 # HTTP
      # - 7473:7473 # HTTPS
      - 7687:7687 # Bolt
    environment:
      NEO4J_AUTH: neo4j/bestia
      # This must be set to the ip of the server to allow the browser to connect to neo4j
      # normal it should be localhost:7687
      NEO4J_dbms_connector_bolt_advertised__address: "192.168.178.220:7687"