version: '3'
services:
  mysql:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bestia
      MYSQL_USER: bestia
      MYSQL_PASSWORD: bestia
      MYSQL_ROOT_PASSWORD: bestia
  cassandra:
    # https://docs.docker.com/samples/library/cassandra/
    image: cassandra:3
    restart: always
    ports:
      - 7000:7000
      - 9042:9042