version: '3'
services:
  mysql:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bestia
      MYSQL_USER: bestia
      MYSQL_PASSWORD: bestia
      MYSQL_ROOT_PASSWORD: bestia
  cassandra:
    # https://docs.docker.com/samples/library/cassandra/
    image: cassandra:3
    restart: always
    ports:
      - 7000:7000
      - 9042:9042
  neo4j:
    # https://neo4j.com/developer/docker-run-neo4j/
    image: neo4j:4.0.4
    ports:
      - 7474:7474 # HTTP
      # - 7473:7473 # HTTPS
      - 7687:7687 # Bolt
    environment:
      NEO4J_AUTH: neo4j/bestia
      NEO4J_dbms_connector_bolt_advertised__address: "localhost:7687"