package net.bestia.worldgen.vector

import java.util.Locale
import kotlin.math.max
import kotlin.math.min
import kotlin.math.sqrt

/**
 * The result of projecting a world position onto a [Polyline].
 *
 * This is the single query that the whole vector feature system rests on. Because it is a
 * continuous function of the query position, and because the polyline is one continuous object
 * in world space that no chunk owns, two adjacent columns generated by two different chunks on
 * two different nodes get results that differ only by the distance between the columns. That is
 * what makes feature geometry C0-continuous across chunk borders by construction rather than by
 * seam stitching. See the "Chunk borders" section of worldgen-architecture.md.
 */
data class Projection(
  /** Arc length of the closest point from the start of the line, in metres. */
  val s: Double,
  /**
   * The same location expressed in station parameter space: `segment + t`, so vertex `i` is at
   * exactly `i`. This is what [StationTable] interpolates over.
   */
  val u: Double,
  /** Unsigned distance from the query position to the line. */
  val distance: Double,
  /** Signed lateral offset; positive when the query position lies left of the direction of travel. */
  val lateral: Double,
  /** The closest point itself. */
  val point: Vec2d,
  /** Index of the segment carrying the closest point. */
  val segment: Int,
  /**
   * True when the closest point is one of the two endpoints *and* the query position projects
   * beyond it, i.e. the position is off the end of the line rather than beside it. Profiles use
   * this to taper out instead of wrapping a corridor around the end cap.
   */
  val beyondEnd: Boolean
)

/**
 * An open polyline in world space, with arc-length parametrization.
 *
 * Consecutive duplicate points are dropped on construction, because a zero-length segment has no
 * direction and would make projection ill-defined.
 */
class Polyline(points: List<Vec2d>) {

  val points: List<Vec2d>

  /** Cumulative arc length at each vertex; `cumulative[0] == 0.0`. */
  private val cumulative: DoubleArray

  val length: Double
  val bbox: Aabb

  init {
    val cleaned = ArrayList<Vec2d>(points.size)
    for (p in points) {
      if (cleaned.isEmpty() || cleaned.last() != p) {
        cleaned.add(p)
      }
    }
    require(cleaned.size >= 2) { "A polyline needs at least two distinct points, got ${cleaned.size}" }

    this.points = cleaned
    this.cumulative = DoubleArray(cleaned.size)
    for (i in 1 until cleaned.size) {
      cumulative[i] = cumulative[i - 1] + cleaned[i - 1].distanceTo(cleaned[i])
    }
    this.length = cumulative[cleaned.size - 1]
    this.bbox = Aabb.around(cleaned)
  }

  val vertexCount get() = points.size
  val segmentCount get() = points.size - 1

  /** Arc length at vertex [index]. */
  fun arcLengthAt(index: Int) = cumulative[index]

  /**
   * Projects [p] onto the line and returns the closest point.
   *
   * Segments are scanned in index order and ties are broken towards the lower index (the
   * comparison is strict), so the result never depends on iteration or thread order.
   */
  fun project(p: Vec2d): Projection {
    var bestDistSq = Double.POSITIVE_INFINITY
    var bestSegment = 0
    var bestT = 0.0
    var bestPoint = points[0]

    for (i in 0 until segmentCount) {
      val a = points[i]
      val b = points[i + 1]
      val abx = b.x - a.x
      val aby = b.y - a.y
      val lenSq = abx * abx + aby * aby
      // lenSq > 0 is guaranteed: the constructor removed duplicate consecutive points.
      var t = ((p.x - a.x) * abx + (p.y - a.y) * aby) / lenSq
      t = if (t < 0.0) 0.0 else if (t > 1.0) 1.0 else t

      val qx = a.x + abx * t
      val qy = a.y + aby * t
      val dx = p.x - qx
      val dy = p.y - qy
      val distSq = dx * dx + dy * dy

      if (distSq < bestDistSq) {
        bestDistSq = distSq
        bestSegment = i
        bestT = t
        bestPoint = Vec2d(qx, qy)
      }
    }

    val a = points[bestSegment]
    val b = points[bestSegment + 1]
    val tangent = (b - a).normalized()
    val toPoint = p - bestPoint
    val lateral = tangent cross toPoint

    val beyondEnd = (bestSegment == 0 && bestT == 0.0 && toPoint.dot(tangent) < 0.0) ||
        (bestSegment == segmentCount - 1 && bestT == 1.0 && toPoint.dot(tangent) > 0.0)

    return Projection(
      s = cumulative[bestSegment] + bestT * (cumulative[bestSegment + 1] - cumulative[bestSegment]),
      u = bestSegment + bestT,
      distance = sqrt(bestDistSq),
      lateral = lateral,
      point = bestPoint,
      segment = bestSegment,
      beyondEnd = beyondEnd
    )
  }

  /** The position at arc length [s], clamped to the ends of the line. */
  fun pointAt(s: Double): Vec2d {
    val clamped = s.coerceIn(0.0, length)
    val i = segmentIndexFor(clamped)
    val segLen = cumulative[i + 1] - cumulative[i]
    val t = if (segLen == 0.0) 0.0 else (clamped - cumulative[i]) / segLen
    return points[i].lerp(points[i + 1], t)
  }

  /** The unit direction of travel at arc length [s]. Piecewise constant, so discontinuous at vertices. */
  fun tangentAt(s: Double): Vec2d {
    val i = segmentIndexFor(s.coerceIn(0.0, length))
    return (points[i + 1] - points[i]).normalized()
  }

  /** Converts arc length to station parameter space (`segment + t`), the domain of [StationTable]. */
  fun stationParamAt(s: Double): Double {
    val clamped = s.coerceIn(0.0, length)
    val i = segmentIndexFor(clamped)
    val segLen = cumulative[i + 1] - cumulative[i]
    val t = if (segLen == 0.0) 0.0 else (clamped - cumulative[i]) / segLen
    return i + t
  }

  private fun segmentIndexFor(s: Double): Int {
    // Binary search for the last vertex whose arc length is <= s.
    var lo = 0
    var hi = points.size - 1
    while (lo < hi) {
      val mid = (lo + hi + 1) ushr 1
      if (cumulative[mid] <= s) lo = mid else hi = mid - 1
    }
    return min(lo, segmentCount - 1)
  }

  /**
   * Resamples the line to uniform [spacing] along arc length, always keeping both endpoints.
   *
   * Feature centerlines are resampled before their [StationTable] is built, because uniform vertex
   * spacing is what makes Catmull-Rom station interpolation well behaved - unevenly spaced control
   * points make a uniform-parametrization spline overshoot around the short segments.
   */
  fun resample(spacing: Double): Polyline {
    require(spacing > 0.0) { "spacing must be positive, was $spacing" }

    val steps = max(1, Math.round(length / spacing).toInt())
    val step = length / steps
    val out = ArrayList<Vec2d>(steps + 1)
    for (i in 0..steps) {
      out.add(pointAt(i * step))
    }

    return Polyline(out)
  }

  /**
   * Chaikin corner cutting. Two or three iterations are enough to take the staircase out of a D8
   * flow path while keeping the endpoints pinned.
   */
  fun chaikin(iterations: Int): Polyline {
    require(iterations >= 0) { "iterations must not be negative, was $iterations" }

    var current = points
    repeat(iterations) {
      val next = ArrayList<Vec2d>(current.size * 2)
      next.add(current.first())
      for (i in 0 until current.size - 1) {
        val a = current[i]
        val b = current[i + 1]
        next.add(a.lerp(b, 0.25))
        next.add(a.lerp(b, 0.75))
      }
      next.add(current.last())
      current = next
    }

    return Polyline(current)
  }

  /**
   * Subdivides each segment with a centripetal-free uniform Catmull-Rom spline through the existing
   * vertices. Unlike [chaikin] this interpolates the control points rather than shrinking towards
   * them, which matters when the vertices are meaningful (a river's confluence node, a road's
   * junction) rather than just a sampled shape.
   */
  fun catmullRomSmooth(subdivisions: Int): Polyline {
    require(subdivisions >= 1) { "subdivisions must be at least 1, was $subdivisions" }
    if (subdivisions == 1) return this

    val out = ArrayList<Vec2d>(segmentCount * subdivisions + 1)
    for (i in 0 until segmentCount) {
      val p0 = points[max(0, i - 1)]
      val p1 = points[i]
      val p2 = points[i + 1]
      val p3 = points[min(points.size - 1, i + 2)]
      for (k in 0 until subdivisions) {
        val t = k.toDouble() / subdivisions
        out.add(
          Vec2d(
            catmullRom(p0.x, p1.x, p2.x, p3.x, t),
            catmullRom(p0.y, p1.y, p2.y, p3.y, t)
          )
        )
      }
    }
    out.add(points.last())

    return Polyline(out)
  }

  /**
   * Offsets every vertex perpendicular to the local tangent by [offset], evaluated as a pure
   * function of the vertex's arc length.
   *
   * This is how meandering is applied - at vector level, on the one continuous centerline, never
   * per chunk. A chunk-level perturbation cannot produce a channel that lines up across a chunk
   * border because each chunk would perturb independently.
   */
  fun offsetLaterally(offset: (s: Double) -> Double): Polyline {
    val out = ArrayList<Vec2d>(points.size)
    for (i in points.indices) {
      val s = cumulative[i]
      val tangent = when (i) {
        0 -> (points[1] - points[0]).normalized()
        points.size - 1 -> (points[i] - points[i - 1]).normalized()
        // Average of the two adjoining segment directions, so the offset curve does not kink.
        else -> ((points[i + 1] - points[i]).normalized() + (points[i] - points[i - 1]).normalized()).normalized()
      }
      out.add(points[i] + tangent.perpendicular() * offset(s))
    }

    return Polyline(out)
  }

  override fun toString() = "Polyline[vertices=${points.size}, length=${"%.1f".format(Locale.ROOT, length)}m]"

  companion object {
    internal fun catmullRom(p0: Double, p1: Double, p2: Double, p3: Double, t: Double): Double {
      val t2 = t * t
      val t3 = t2 * t
      return 0.5 * (
          2.0 * p1 +
              (-p0 + p2) * t +
              (2.0 * p0 - 5.0 * p1 + 4.0 * p2 - p3) * t2 +
              (-p0 + 3.0 * p1 - 3.0 * p2 + p3) * t3
          )
    }
  }
}
