package net.bestia.zone.navigation.graph

import io.github.oshai.kotlinlogging.KotlinLogging
import net.bestia.worldgen.core.ChunkPos
import net.bestia.worldgen.core.NavEdgeKind
import net.bestia.zone.navigation.NavigationConfig
import net.bestia.zone.navigation.local.LocalWalkQuery
import net.bestia.zone.navigation.profile.MovementProfile
import org.springframework.stereotype.Service

/**
 * The live macro graph: the generated routes, plus what has happened to them since.
 *
 * ### Base plus overlay, never a rebuild
 *
 * The generated graph is immutable, and a destroyed bridge does not change it - it changes whether one edge is
 * currently usable, which is a bit in [blocked]. This is the same base-plus-delta split `ChunkStore` uses for
 * voxels and `DerivedStore` uses for walkability, and here it is what makes the whole update story affordable:
 * a voxel edit costs a set membership test and possibly one queued edge, never a re-derivation of anything.
 *
 * Recomputing the graph on an edit was the alternative and it is the one thing that would genuinely be too
 * expensive - players edit voxels many times a second, and the graph takes seconds to build.
 *
 * ### Deliberately not instant
 *
 * An edit only *queues* the edges over it. [revalidate] spends a bounded budget, called every few seconds
 * rather than every tick, because a bridge collapsing is a rare discrete event and not the per-tick stream of
 * voxel edits `DerivedStore` was written for. NPCs therefore learn about it within seconds - which is what the
 * requirements ask for - and the population adopts it staggered on top of that, see [version].
 */
@Service
class MacroGraphService(
  private val world: NavWorldSource,
  private val walkQuery: LocalWalkQuery,
  private val config: NavigationConfig
) {

  private var graphOrNull: RuntimeNavGraph? = null

  /** Set once the world is loaded; until then every query answers "no route". */
  val graph: RuntimeNavGraph get() = graphOrNull ?: RuntimeNavGraph.EMPTY

  val isReady get() = graphOrNull != null

  /**
   * How many times the usable set has changed.
   *
   * An NPC records this on the route it planned. When the two differ its route is *stale*, which is not the
   * same as wrong - the change may be nowhere near it - so it does not replan on the spot; it schedules one
   * for a random moment inside [NavigationConfig.macroReplanJitterSeconds]. That is what stops every traveller
   * in the world from replanning on the tick a single bridge falls, and it is also why NPCs visibly disagree
   * about the news for a while, which is the behaviour that was asked for.
   */
  private var currentVersion = 0L

  val version: Long get() = currentVersion

  private var blocked = BooleanArray(0)

  /** Edges whose usability is in doubt, oldest first. */
  private val staleEdges = LinkedHashSet<Int>()

  /**
   * Structural edges by the chunk they pass through.
   *
   * Only structural kinds are indexed - a road, a bridge, a gate spoke - because those are the edges an edit
   * can actually sever. Indexing wilderness edges too would mean every hillside a player terraces queues a
   * batch of open-country hops whose answer is "you can still walk round", and there are two orders of
   * magnitude more of them.
   */
  private var edgesByChunk: Map<ChunkPos, IntArray> = emptyMap()

  /**
   * Builds the runtime graph and subscribes to chunk edits.
   *
   * Called on first use rather than from a constructor or `@PostConstruct`, because the world is generated by
   * a boot runner and the tick loop is a boot runner too - a bean that needed terrain at construction time
   * would either generate a world on the wrong thread or lose the race.
   */
  fun ensureLoaded() {
    if (graphOrNull != null || !world.isReady) return

    val runtime = RuntimeNavGraph.of(world.navGraph(), world::place)

    graphOrNull = runtime
    blocked = BooleanArray(runtime.edges.size)
    edgesByChunk = indexStructuralEdges(runtime)

    world.onChunkChanged { chunk -> onChunkChanged(chunk) }

    LOG.info {
      "Navigation graph ready: ${runtime.nodeCount} nodes, ${runtime.edges.size} edges, " +
          "${edgesByChunk.size} chunks carrying structural routes"
    }
  }

  fun isBlocked(edgeIndex: Int): Boolean = blocked.getOrNull(edgeIndex) ?: false

  /** A pathfinder over the current graph for one creature. */
  fun pathfinderFor(profile: MovementProfile): MacroPathfinder =
    MacroPathfinder(graph, profile, ::isBlocked)

  val pendingRevalidations get() = staleEdges.size

  /**
   * Re-tests up to [budget] queued edges against the ground as it is now.
   *
   * The test reuses the same [LocalWalkQuery] the local pathfinder uses - there is no second notion of
   * "passable" to drift out of step - and it probes only *within the edge's own span*, not "is there any route
   * from one end to the other". The latter would almost always say yes, by going round, and then no edge would
   * ever be marked blocked at all.
   *
   * @return how many were re-tested, so a caller can tell whether it is keeping up
   */
  fun revalidate(budget: Int = config.macroRevalidationsPerPass): Int {
    if (graphOrNull == null || budget <= 0 || staleEdges.isEmpty()) return 0

    var done = 0
    var changed = false
    val iterator = staleEdges.iterator()

    while (done < budget && iterator.hasNext()) {
      val edgeIndex = iterator.next()
      iterator.remove()
      done++

      val edge = graph.edges.getOrNull(edgeIndex) ?: continue
      val nowBlocked = !isStillPassable(edge)

      if (blocked[edgeIndex] != nowBlocked) {
        blocked[edgeIndex] = nowBlocked
        changed = true
        LOG.debug { "Macro edge $edgeIndex ($edge) is now ${if (nowBlocked) "blocked" else "open"}" }
      }
    }

    // One bump per pass rather than per edge: a collapsing bridge is several edges at once, and a version per
    // edge would make every traveller schedule several replans for what is one piece of news.
    if (changed) currentVersion++

    return done
  }

  /**
   * Whether every step along an edge's own waypoints is still walkable.
   *
   * A structural edge is a *specific* built thing, so the question is whether that thing is still there.
   * Sampled along the waypoints the generator emitted; a stretch whose chunks are not resident is treated as
   * still passable, because "nobody is looking at it" is not evidence that it fell down.
   */
  private fun isStillPassable(edge: RuntimeNavEdge): Boolean {
    val points = buildList {
      add(graph.nodePositions[edge.a])
      addAll(edge.waypoints)
      add(graph.nodePositions[edge.b])
    }

    for (i in 1 until points.size) {
      val from = points[i - 1]
      val to = points[i]
      if (!walkQuery.isResident(from) || !walkQuery.isResident(to)) continue

      // Adjacent waypoints are far apart - a road's are a couple of hundred metres - so `canStep` cannot be
      // asked directly. What is checked is that both ends are still standable ground; a deck that was removed
      // leaves its columns with no walkable span over the water, which is exactly this test failing.
      if (walkQuery.surfaceAt(from) == null || walkQuery.surfaceAt(to) == null) return false
    }

    return true
  }

  private fun onChunkChanged(chunk: ChunkPos) {
    val affected = edgesByChunk[chunk] ?: return
    for (edgeIndex in affected) staleEdges.add(edgeIndex)
  }

  /**
   * Which chunks each structural edge passes through.
   *
   * Built once, from the edge's own waypoints. An edge with no waypoints contributes only its endpoints, which
   * is right for the short straight edges that have none - a bridge and a gate spoke.
   */
  private fun indexStructuralEdges(runtime: RuntimeNavGraph): Map<ChunkPos, IntArray> {
    val buckets = HashMap<ChunkPos, MutableList<Int>>()

    for ((index, edge) in runtime.edges.withIndex()) {
      if (!edge.isStructural) continue

      val points = buildList {
        add(runtime.nodePositions[edge.a])
        addAll(edge.waypoints)
        add(runtime.nodePositions[edge.b])
      }

      for (point in points) {
        val chunk = world.chunkAt(point) ?: continue
        val bucket = buckets.getOrPut(chunk) { ArrayList() }
        if (bucket.lastOrNull() != index) bucket.add(index)
      }
    }

    return buckets.mapValues { (_, list) -> list.distinct().toIntArray() }
  }

  private companion object {
    private val LOG = KotlinLogging.logger { }
  }
}

/** True for the edges a chunk edit can actually sever: the built ones. */
private val RuntimeNavEdge.isStructural: Boolean
  get() = kind == NavEdgeKind.ROAD || kind == NavEdgeKind.BRIDGE || kind == NavEdgeKind.GATE_SPOKE
