package net.bestia.zone.world

import io.github.oshai.kotlinlogging.KotlinLogging
import net.bestia.worldgen.core.StageListener
import net.bestia.worldgen.core.CellRegion
import net.bestia.worldgen.core.Stage
import net.bestia.worldgen.core.StageResult
import net.bestia.worldgen.core.WorldConfig
import net.bestia.worldgen.pipeline.GeneratedWorld
import net.bestia.worldgen.pipeline.StandardWorld
import net.bestia.worldgen.store.PipelineVersion
import net.bestia.worldgen.store.VersionGate
import net.bestia.worldgen.voxel.ChunkMaterializer
import net.bestia.zone.BestiaException
import org.springframework.stereotype.Service

/**
 * Thrown when the running build cannot generate the stored world's terrain.
 *
 * A hard failure on purpose. The alternative is to boot anyway and serve a world whose ground does not match
 * what its player edits were made against, which surfaces as buildings floating over new terrain and holes
 * where somebody's floor used to be - and by then the old base is gone and there is nothing to migrate from.
 */
class IncompatibleWorldException(message: String) : BestiaException(CODE, message) {
  companion object {
    const val CODE = "WORLD_PIPELINE_MISMATCH"
  }
}

/**
 * Owns the world: its record, and the generated terrain tier built from it.
 *
 * The terrain is **regenerated at boot rather than loaded**, which is worth stating plainly because it looks
 * like a missing feature. Rasters and vector features are a pure function of the seed and the dimensions in
 * [PersistedWorld], so storing them would be storing a cache - and a cache with a correctness risk, since a
 * stale copy is indistinguishable from a fresh one. What players change is stored; what the seed implies is
 * computed. A 128 km world takes about a second.
 *
 * Not thread safe to load; safe to read once loaded, since the world tier is immutable.
 */
@Service
class WorldService(
  private val provisioning: WorldProvisioning,
  private val settings: WorldGenConfig
) {

  private class Loaded(
    val record: PersistedWorld,
    val generated: GeneratedWorld
  )

  @Volatile
  private var loaded: Loaded? = null

  val isLoaded get() = loaded != null

  /** The world's identity and birth settings. */
  val record: PersistedWorld get() = require().record

  /** The generated world tier plus the samplers that materialise chunks from it. */
  val generated: GeneratedWorld get() = require().generated

  val config: WorldConfig get() = require().generated.config

  val materializer: ChunkMaterializer get() = require().generated.materializer

  /**
   * Finds or creates the world record, checks this build can generate it, and builds the terrain.
   *
   * Idempotent: calling it again once loaded does nothing, so a second boot runner or a test that wants the
   * world present cannot accidentally regenerate it.
   */
  fun load() {
    if (loaded != null) return

    val record = provisioning.findOrCreate()
    val config = record.toWorldConfig()
    verifyCompatible(record, config)

    val startedAt = System.nanoTime()
    val generated = StandardWorld.build(config, LoggingStageListener)
    val millis = (System.nanoTime() - startedAt) / 1_000_000

    loaded = Loaded(record, generated)

    LOG.info {
      "World '${record.name}' ready in $millis ms: " +
          "${generated.world.features.all().size} vector features, " +
          "${(record.widthMetres / 1000).toInt()}x${(record.heightMetres / 1000).toInt()} km"
    }
  }

  /**
   * Whether this build generates the same terrain the world was born with.
   *
   * Reuses the client/server gate, because the question is identical - two independently generating parties
   * either agree or they do not - and it reports which of the three components disagrees rather than a single
   * useless "incompatible". Here the stored world plays the part of the party that must match.
   */
  private fun verifyCompatible(record: PersistedWorld, config: WorldConfig) {
    val current = PipelineVersion.current(StandardWorld.pipeline(config).pipelineVersion)
    val stored = PipelineVersion(
      pipelineVersion = record.pipelineVersion,
      blockPaletteVersion = record.blockPaletteVersion,
      chunkFormatVersion = record.chunkFormatVersion
    )

    when (val verdict = VersionGate.check(server = current, client = stored)) {
      is VersionGate.Verdict.Compatible, VersionGate.Verdict.ServerAuthoritativeOnly -> Unit

      is VersionGate.Verdict.Incompatible -> {
        val message = "World '${record.name}' was generated by a different pipeline: ${verdict.reason}. " +
            "Stored $stored, this build $current. Any player edits in this world are deltas over the old " +
            "base, so regenerating against the new one would move the ground under them. Bake the modified " +
            "chunks before changing the pipeline, or start a new world."

        if (settings.refuseOnPipelineMismatch) {
          throw IncompatibleWorldException(message)
        }
        LOG.error { "$message Continuing because worldgen.refuse-on-pipeline-mismatch is off." }
      }
    }
  }

  private fun require(): Loaded = loaded
    ?: throw IllegalStateException("The world has not been loaded yet; WorldService.load() runs at boot")

  /** Per-stage timings, so a slow boot can be attributed rather than guessed at. */
  private object LoggingStageListener : StageListener {
    override fun onStageFinish(stage: Stage, region: CellRegion, result: StageResult, millis: Long) {
      LOG.debug { "  ${stage.id.name} in $millis ms" }
    }
  }

  private companion object {
    private val LOG = KotlinLogging.logger { }
  }
}
