# ===============================
# = LOGGING
# ===============================
logging:
  level:
    ROOT: WARN
    net.bestia: DEBUG
    de.tfelix.bestia: DEBUG

# ===============================
# = LIBRARIES
# ===============================
spring:
  datasource:
    url: jdbc:mysql://192.168.178.220:3306/bestia?serverTimezone=UTC
    username: bestia
    password: bestia
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      jdbc.time_zone: UTC
    properties.hibernate.dialect: org.hibernate.dialect.MariaDB53Dialect

  flyway:
    enabled: true
    baselineOnMigrate: true