// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages/map/chunk_static_entities_smsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bnet {

  /// <summary>Holder for reflection information generated from messages/map/chunk_static_entities_smsg.proto</summary>
  public static partial class ChunkStaticEntitiesSmsgReflection {

    #region Descriptor
    /// <summary>File descriptor for messages/map/chunk_static_entities_smsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChunkStaticEntitiesSmsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1tZXNzYWdlcy9tYXAvY2h1bmtfc3RhdGljX2VudGl0aWVzX3Ntc2cucHJv",
            "dG8SBGJuZXQaGG1lc3NhZ2VzL21hcC9jaHVuay5wcm90byKCAgoXQ2h1bmtT",
            "dGF0aWNFbnRpdGllc1NNU0cSGwoDcG9zGAEgASgLMg4uYm5ldC5DaHVua1Bv",
            "cxI0CgdlbnRyaWVzGAIgAygLMiMuYm5ldC5DaHVua1N0YXRpY0VudGl0aWVz",
            "U01TRy5FbnRyeRqTAQoFRW50cnkSEQoJZW50aXR5X2lkGAEgASgGEgwKBGtp",
            "bmQYAiABKA0SDwoHdmFyaWFudBgDIAEoDRIPCgdsb2NhbF94GAQgASgNEg8K",
            "B2xvY2FsX3kYBSABKA0SCQoBehgGIAEoERIRCgloZWlnaHRfZG0YByABKA0S",
            "GAoQeWF3X2NlbnRpcmFkaWFucxgIIAEoDUI1ChVuZXQuYmVzdGlhLmJuZXQu",
            "cHJvdG9CHENodW5rU3RhdGljRW50aXRpZXNTTVNHUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Bnet.ChunkReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Bnet.ChunkStaticEntitiesSMSG), global::Bnet.ChunkStaticEntitiesSMSG.Parser, new[]{ "Pos", "Entries" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Bnet.ChunkStaticEntitiesSMSG.Types.Entry), global::Bnet.ChunkStaticEntitiesSMSG.Types.Entry.Parser, new[]{ "EntityId", "Kind", "Variant", "LocalX", "LocalY", "Z", "HeightDm", "YawCentiradians" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///*
  /// Every static entity standing in one chunk column, in one message.
  ///
  /// ### Why these do not travel as entities
  ///
  /// A static entity is a real ECS entity and could be synced the ordinary way, one component message at a
  /// time. Measured, that costs **78 bytes across three separate `writeAndFlush` calls** per entity - a
  /// position, a visual and a health - and a player's view volume holds one to seven thousand trees depending
  /// on the lattice. So the ordinary path is five to twenty thousand *flushes* for one login, against 121 for
  /// the entire world's terrain in the same volume.
  ///
  /// The bytes were never the problem. Batched at about 25 bytes an entry this is 44 kB for an 8 m lattice
  /// against ~375 kB of chunk payload for the same 121 chunks, and steady state as a player walks is a couple
  /// of kilobytes per chunk boundary crossed.
  ///
  /// ### Delivery is co-terminous with terrain by construction
  ///
  /// One of these follows each chunk payload, and it is dropped when that chunk leaves the manifest. So the
  /// range entities appear at is the range the ground appears at, without a second radius that has to be kept
  /// in step with the first - and removal needs no vanish message, because the client already discards a
  /// chunk's contents when the manifest withdraws it.
  ///
  /// ### Ids here are not durable
  ///
  /// `entity_id` is a live ECS id and is re-minted every time the chunk is re-materialised, because the server
  /// destroys a column's entities when the last client stops holding it. A client must treat these as valid
  /// only for as long as it holds the chunk, and must not persist one or carry it across a re-send. It is a
  /// handle for "the thing I am pointing at right now", which is all a click needs.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ChunkStaticEntitiesSMSG : pb::IMessage<ChunkStaticEntitiesSMSG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChunkStaticEntitiesSMSG> _parser = new pb::MessageParser<ChunkStaticEntitiesSMSG>(() => new ChunkStaticEntitiesSMSG());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChunkStaticEntitiesSMSG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bnet.ChunkStaticEntitiesSmsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChunkStaticEntitiesSMSG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChunkStaticEntitiesSMSG(ChunkStaticEntitiesSMSG other) : this() {
      pos_ = other.pos_ != null ? other.pos_.Clone() : null;
      entries_ = other.entries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChunkStaticEntitiesSMSG Clone() {
      return new ChunkStaticEntitiesSMSG(this);
    }

    /// <summary>Field number for the "pos" field.</summary>
    public const int PosFieldNumber = 1;
    private global::Bnet.ChunkPos pos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bnet.ChunkPos Pos {
      get { return pos_; }
      set {
        pos_ = value;
      }
    }

    /// <summary>Field number for the "entries" field.</summary>
    public const int EntriesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Bnet.ChunkStaticEntitiesSMSG.Types.Entry> _repeated_entries_codec
        = pb::FieldCodec.ForMessage(18, global::Bnet.ChunkStaticEntitiesSMSG.Types.Entry.Parser);
    private readonly pbc::RepeatedField<global::Bnet.ChunkStaticEntitiesSMSG.Types.Entry> entries_ = new pbc::RepeatedField<global::Bnet.ChunkStaticEntitiesSMSG.Types.Entry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Bnet.ChunkStaticEntitiesSMSG.Types.Entry> Entries {
      get { return entries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChunkStaticEntitiesSMSG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChunkStaticEntitiesSMSG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Pos, other.Pos)) return false;
      if(!entries_.Equals(other.entries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (pos_ != null) hash ^= Pos.GetHashCode();
      hash ^= entries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (pos_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Pos);
      }
      entries_.WriteTo(output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (pos_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Pos);
      }
      entries_.WriteTo(ref output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (pos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pos);
      }
      size += entries_.CalculateSize(_repeated_entries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChunkStaticEntitiesSMSG other) {
      if (other == null) {
        return;
      }
      if (other.pos_ != null) {
        if (pos_ == null) {
          Pos = new global::Bnet.ChunkPos();
        }
        Pos.MergeFrom(other.Pos);
      }
      entries_.Add(other.entries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (pos_ == null) {
              Pos = new global::Bnet.ChunkPos();
            }
            input.ReadMessage(Pos);
            break;
          }
          case 18: {
            entries_.AddEntriesFrom(input, _repeated_entries_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (pos_ == null) {
              Pos = new global::Bnet.ChunkPos();
            }
            input.ReadMessage(Pos);
            break;
          }
          case 18: {
            entries_.AddEntriesFrom(ref input, _repeated_entries_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ChunkStaticEntitiesSMSG message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      ///*
      /// One placed object.
      ///
      /// Positions are **local to the chunk** in the horizontal, which is what keeps an entry at 25 bytes: a
      /// world x on a 128 km world is a three-byte varint and a local one is a single byte. `z` stays global,
      /// because a chunk column spans the whole vertical extent and a slab-local z would need the slab index
      /// to be meaningful.
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Entry : pb::IMessage<Entry>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Entry> _parser = new pb::MessageParser<Entry>(() => new Entry());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Entry> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Bnet.ChunkStaticEntitiesSMSG.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Entry() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Entry(Entry other) : this() {
          entityId_ = other.entityId_;
          kind_ = other.kind_;
          variant_ = other.variant_;
          localX_ = other.localX_;
          localY_ = other.localY_;
          z_ = other.z_;
          heightDm_ = other.heightDm_;
          yawCentiradians_ = other.yawCentiradians_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Entry Clone() {
          return new Entry(this);
        }

        /// <summary>Field number for the "entity_id" field.</summary>
        public const int EntityIdFieldNumber = 1;
        private ulong entityId_;
        /// <summary>
        ///* Live ECS id. Fixed rather than varint: a snowflake is ~4.3e16, so a varint would spend nine bytes. 
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong EntityId {
          get { return entityId_; }
          set {
            entityId_ = value;
          }
        }

        /// <summary>Field number for the "kind" field.</summary>
        public const int KindFieldNumber = 2;
        private uint kind_;
        /// <summary>
        ///* `StaticEntityKind` ordinal. The client dispatches on this to pick a mesh. 
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Kind {
          get { return kind_; }
          set {
            kind_ = value;
          }
        }

        /// <summary>Field number for the "variant" field.</summary>
        public const int VariantFieldNumber = 3;
        private uint variant_;
        /// <summary>
        ///* Which of a kind's interchangeable meshes, so a wood is not one tree repeated. 
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Variant {
          get { return variant_; }
          set {
            variant_ = value;
          }
        }

        /// <summary>Field number for the "local_x" field.</summary>
        public const int LocalXFieldNumber = 4;
        private uint localX_;
        /// <summary>
        ///* Voxel column inside the chunk, `0..chunkSize-1`. 
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint LocalX {
          get { return localX_; }
          set {
            localX_ = value;
          }
        }

        /// <summary>Field number for the "local_y" field.</summary>
        public const int LocalYFieldNumber = 5;
        private uint localY_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint LocalY {
          get { return localY_; }
          set {
            localY_ = value;
          }
        }

        /// <summary>Field number for the "z" field.</summary>
        public const int ZFieldNumber = 6;
        private int z_;
        /// <summary>
        ///* Global voxel z of the ground it stands on. Signed, because the seabed is below zero. 
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Z {
          get { return z_; }
          set {
            z_ = value;
          }
        }

        /// <summary>Field number for the "height_dm" field.</summary>
        public const int HeightDmFieldNumber = 7;
        private uint heightDm_;
        /// <summary>
        ///* Height in decimetres. Finer than anyone can see at a metre per voxel, and a third of an int. 
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint HeightDm {
          get { return heightDm_; }
          set {
            heightDm_ = value;
          }
        }

        /// <summary>Field number for the "yaw_centiradians" field.</summary>
        public const int YawCentiradiansFieldNumber = 8;
        private uint yawCentiradians_;
        /// <summary>
        ///* Facing, in hundredths of a radian. A tree does not need more and a byte and a half is plenty. 
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint YawCentiradians {
          get { return yawCentiradians_; }
          set {
            yawCentiradians_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Entry);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Entry other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (EntityId != other.EntityId) return false;
          if (Kind != other.Kind) return false;
          if (Variant != other.Variant) return false;
          if (LocalX != other.LocalX) return false;
          if (LocalY != other.LocalY) return false;
          if (Z != other.Z) return false;
          if (HeightDm != other.HeightDm) return false;
          if (YawCentiradians != other.YawCentiradians) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (EntityId != 0UL) hash ^= EntityId.GetHashCode();
          if (Kind != 0) hash ^= Kind.GetHashCode();
          if (Variant != 0) hash ^= Variant.GetHashCode();
          if (LocalX != 0) hash ^= LocalX.GetHashCode();
          if (LocalY != 0) hash ^= LocalY.GetHashCode();
          if (Z != 0) hash ^= Z.GetHashCode();
          if (HeightDm != 0) hash ^= HeightDm.GetHashCode();
          if (YawCentiradians != 0) hash ^= YawCentiradians.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (EntityId != 0UL) {
            output.WriteRawTag(9);
            output.WriteFixed64(EntityId);
          }
          if (Kind != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(Kind);
          }
          if (Variant != 0) {
            output.WriteRawTag(24);
            output.WriteUInt32(Variant);
          }
          if (LocalX != 0) {
            output.WriteRawTag(32);
            output.WriteUInt32(LocalX);
          }
          if (LocalY != 0) {
            output.WriteRawTag(40);
            output.WriteUInt32(LocalY);
          }
          if (Z != 0) {
            output.WriteRawTag(48);
            output.WriteSInt32(Z);
          }
          if (HeightDm != 0) {
            output.WriteRawTag(56);
            output.WriteUInt32(HeightDm);
          }
          if (YawCentiradians != 0) {
            output.WriteRawTag(64);
            output.WriteUInt32(YawCentiradians);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (EntityId != 0UL) {
            output.WriteRawTag(9);
            output.WriteFixed64(EntityId);
          }
          if (Kind != 0) {
            output.WriteRawTag(16);
            output.WriteUInt32(Kind);
          }
          if (Variant != 0) {
            output.WriteRawTag(24);
            output.WriteUInt32(Variant);
          }
          if (LocalX != 0) {
            output.WriteRawTag(32);
            output.WriteUInt32(LocalX);
          }
          if (LocalY != 0) {
            output.WriteRawTag(40);
            output.WriteUInt32(LocalY);
          }
          if (Z != 0) {
            output.WriteRawTag(48);
            output.WriteSInt32(Z);
          }
          if (HeightDm != 0) {
            output.WriteRawTag(56);
            output.WriteUInt32(HeightDm);
          }
          if (YawCentiradians != 0) {
            output.WriteRawTag(64);
            output.WriteUInt32(YawCentiradians);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (EntityId != 0UL) {
            size += 1 + 8;
          }
          if (Kind != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Kind);
          }
          if (Variant != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Variant);
          }
          if (LocalX != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LocalX);
          }
          if (LocalY != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LocalY);
          }
          if (Z != 0) {
            size += 1 + pb::CodedOutputStream.ComputeSInt32Size(Z);
          }
          if (HeightDm != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HeightDm);
          }
          if (YawCentiradians != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(YawCentiradians);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Entry other) {
          if (other == null) {
            return;
          }
          if (other.EntityId != 0UL) {
            EntityId = other.EntityId;
          }
          if (other.Kind != 0) {
            Kind = other.Kind;
          }
          if (other.Variant != 0) {
            Variant = other.Variant;
          }
          if (other.LocalX != 0) {
            LocalX = other.LocalX;
          }
          if (other.LocalY != 0) {
            LocalY = other.LocalY;
          }
          if (other.Z != 0) {
            Z = other.Z;
          }
          if (other.HeightDm != 0) {
            HeightDm = other.HeightDm;
          }
          if (other.YawCentiradians != 0) {
            YawCentiradians = other.YawCentiradians;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 9: {
                EntityId = input.ReadFixed64();
                break;
              }
              case 16: {
                Kind = input.ReadUInt32();
                break;
              }
              case 24: {
                Variant = input.ReadUInt32();
                break;
              }
              case 32: {
                LocalX = input.ReadUInt32();
                break;
              }
              case 40: {
                LocalY = input.ReadUInt32();
                break;
              }
              case 48: {
                Z = input.ReadSInt32();
                break;
              }
              case 56: {
                HeightDm = input.ReadUInt32();
                break;
              }
              case 64: {
                YawCentiradians = input.ReadUInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 9: {
                EntityId = input.ReadFixed64();
                break;
              }
              case 16: {
                Kind = input.ReadUInt32();
                break;
              }
              case 24: {
                Variant = input.ReadUInt32();
                break;
              }
              case 32: {
                LocalX = input.ReadUInt32();
                break;
              }
              case 40: {
                LocalY = input.ReadUInt32();
                break;
              }
              case 48: {
                Z = input.ReadSInt32();
                break;
              }
              case 56: {
                HeightDm = input.ReadUInt32();
                break;
              }
              case 64: {
                YawCentiradians = input.ReadUInt32();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
