// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages/master/create_master_cmsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bnet {

  /// <summary>Holder for reflection information generated from messages/master/create_master_cmsg.proto</summary>
  public static partial class CreateMasterCmsgReflection {

    #region Descriptor
    /// <summary>File descriptor for messages/master/create_master_cmsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CreateMasterCmsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CihtZXNzYWdlcy9tYXN0ZXIvY3JlYXRlX21hc3Rlcl9jbXNnLnByb3RvEgRi",
            "bmV0GhxtZXNzYWdlcy9tYXN0ZXIvbWFzdGVyLnByb3RvIrkBChBDcmVhdGVN",
            "YXN0ZXJDTVNHEgwKBG5hbWUYASABKAkSHAoEYm9keRgCIAEoDjIOLmJuZXQu",
            "Qm9keVR5cGUSGAoEZmFjZRgDIAEoDjIKLmJuZXQuRmFjZRIdCgRoYWlyGAQg",
            "ASgOMg8uYm5ldC5IYWlyc3R5bGUSHwoKc2tpbl9jb2xvchgFIAEoCzILLmJu",
            "ZXQuQ29sb3ISHwoKaGFpcl9jb2xvchgGIAEoCzILLmJuZXQuQ29sb3JCKgoV",
            "bmV0LmJlc3RpYS5ibmV0LnByb3RvQhFDcmVhdGVNYXN0ZXJQcm90b2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Bnet.MasterReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Bnet.CreateMasterCMSG), global::Bnet.CreateMasterCMSG.Parser, new[]{ "Name", "Body", "Face", "Hair", "SkinColor", "HairColor" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///*
  /// Requests the server to create a new master (character) for the current account.
  /// The result is reported back via OperationSuccess (MASTER_CREATED) or OperationError.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CreateMasterCMSG : pb::IMessage<CreateMasterCMSG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateMasterCMSG> _parser = new pb::MessageParser<CreateMasterCMSG>(() => new CreateMasterCMSG());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CreateMasterCMSG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bnet.CreateMasterCmsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateMasterCMSG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateMasterCMSG(CreateMasterCMSG other) : this() {
      name_ = other.name_;
      body_ = other.body_;
      face_ = other.face_;
      hair_ = other.hair_;
      skinColor_ = other.skinColor_ != null ? other.skinColor_.Clone() : null;
      hairColor_ = other.hairColor_ != null ? other.hairColor_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateMasterCMSG Clone() {
      return new CreateMasterCMSG(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "body" field.</summary>
    public const int BodyFieldNumber = 2;
    private global::Bnet.BodyType body_ = global::Bnet.BodyType.BodyM1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bnet.BodyType Body {
      get { return body_; }
      set {
        body_ = value;
      }
    }

    /// <summary>Field number for the "face" field.</summary>
    public const int FaceFieldNumber = 3;
    private global::Bnet.Face face_ = global::Bnet.Face._1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bnet.Face Face {
      get { return face_; }
      set {
        face_ = value;
      }
    }

    /// <summary>Field number for the "hair" field.</summary>
    public const int HairFieldNumber = 4;
    private global::Bnet.Hairstyle hair_ = global::Bnet.Hairstyle.Hair1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bnet.Hairstyle Hair {
      get { return hair_; }
      set {
        hair_ = value;
      }
    }

    /// <summary>Field number for the "skin_color" field.</summary>
    public const int SkinColorFieldNumber = 5;
    private global::Bnet.Color skinColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bnet.Color SkinColor {
      get { return skinColor_; }
      set {
        skinColor_ = value;
      }
    }

    /// <summary>Field number for the "hair_color" field.</summary>
    public const int HairColorFieldNumber = 6;
    private global::Bnet.Color hairColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bnet.Color HairColor {
      get { return hairColor_; }
      set {
        hairColor_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CreateMasterCMSG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CreateMasterCMSG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Body != other.Body) return false;
      if (Face != other.Face) return false;
      if (Hair != other.Hair) return false;
      if (!object.Equals(SkinColor, other.SkinColor)) return false;
      if (!object.Equals(HairColor, other.HairColor)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Body != global::Bnet.BodyType.BodyM1) hash ^= Body.GetHashCode();
      if (Face != global::Bnet.Face._1) hash ^= Face.GetHashCode();
      if (Hair != global::Bnet.Hairstyle.Hair1) hash ^= Hair.GetHashCode();
      if (skinColor_ != null) hash ^= SkinColor.GetHashCode();
      if (hairColor_ != null) hash ^= HairColor.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Body != global::Bnet.BodyType.BodyM1) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Body);
      }
      if (Face != global::Bnet.Face._1) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Face);
      }
      if (Hair != global::Bnet.Hairstyle.Hair1) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Hair);
      }
      if (skinColor_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(SkinColor);
      }
      if (hairColor_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(HairColor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Body != global::Bnet.BodyType.BodyM1) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Body);
      }
      if (Face != global::Bnet.Face._1) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Face);
      }
      if (Hair != global::Bnet.Hairstyle.Hair1) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Hair);
      }
      if (skinColor_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(SkinColor);
      }
      if (hairColor_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(HairColor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Body != global::Bnet.BodyType.BodyM1) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Body);
      }
      if (Face != global::Bnet.Face._1) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Face);
      }
      if (Hair != global::Bnet.Hairstyle.Hair1) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Hair);
      }
      if (skinColor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SkinColor);
      }
      if (hairColor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HairColor);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CreateMasterCMSG other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Body != global::Bnet.BodyType.BodyM1) {
        Body = other.Body;
      }
      if (other.Face != global::Bnet.Face._1) {
        Face = other.Face;
      }
      if (other.Hair != global::Bnet.Hairstyle.Hair1) {
        Hair = other.Hair;
      }
      if (other.skinColor_ != null) {
        if (skinColor_ == null) {
          SkinColor = new global::Bnet.Color();
        }
        SkinColor.MergeFrom(other.SkinColor);
      }
      if (other.hairColor_ != null) {
        if (hairColor_ == null) {
          HairColor = new global::Bnet.Color();
        }
        HairColor.MergeFrom(other.HairColor);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Body = (global::Bnet.BodyType) input.ReadEnum();
            break;
          }
          case 24: {
            Face = (global::Bnet.Face) input.ReadEnum();
            break;
          }
          case 32: {
            Hair = (global::Bnet.Hairstyle) input.ReadEnum();
            break;
          }
          case 42: {
            if (skinColor_ == null) {
              SkinColor = new global::Bnet.Color();
            }
            input.ReadMessage(SkinColor);
            break;
          }
          case 50: {
            if (hairColor_ == null) {
              HairColor = new global::Bnet.Color();
            }
            input.ReadMessage(HairColor);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Body = (global::Bnet.BodyType) input.ReadEnum();
            break;
          }
          case 24: {
            Face = (global::Bnet.Face) input.ReadEnum();
            break;
          }
          case 32: {
            Hair = (global::Bnet.Hairstyle) input.ReadEnum();
            break;
          }
          case 42: {
            if (skinColor_ == null) {
              SkinColor = new global::Bnet.Color();
            }
            input.ReadMessage(SkinColor);
            break;
          }
          case 50: {
            if (hairColor_ == null) {
              HairColor = new global::Bnet.Color();
            }
            input.ReadMessage(HairColor);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
