// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages/system/dialog_smsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bnet {

  /// <summary>Holder for reflection information generated from messages/system/dialog_smsg.proto</summary>
  public static partial class DialogSmsgReflection {

    #region Descriptor
    /// <summary>File descriptor for messages/system/dialog_smsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DialogSmsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFtZXNzYWdlcy9zeXN0ZW0vZGlhbG9nX3Ntc2cucHJvdG8SBGJuZXQicgoJ",
            "RGlhbG9nQXJnEg4KBHRleHQYASABKAlIABIQCgZudW1iZXIYAiABKANIABIT",
            "CgllbnRpdHlfaWQYAyABKARIABIRCgdpdGVtX2lkGAQgASgDSAASEgoIc2tp",
            "bGxfaWQYBSABKANIAEIHCgV2YWx1ZSLbAQoKRGlhbG9nU01TRxIRCglkaWFs",
            "b2dfaWQYASABKA0SHgoEdHlwZRgCIAEoDjIQLmJuZXQuRGlhbG9nVHlwZRIo",
            "CgRhcmdzGAMgAygLMhouYm5ldC5EaWFsb2dTTVNHLkFyZ3NFbnRyeRIdChBz",
            "b3VyY2VfZW50aXR5X2lkGAQgASgESACIAQEaPAoJQXJnc0VudHJ5EgsKA2tl",
            "eRgBIAEoCRIeCgV2YWx1ZRgCIAEoCzIPLmJuZXQuRGlhbG9nQXJnOgI4AUIT",
            "ChFfc291cmNlX2VudGl0eV9pZCoZCgpEaWFsb2dUeXBlEgsKB0NPTkZJUk0Q",
            "AEIoChVuZXQuYmVzdGlhLmJuZXQucHJvdG9CD0RpYWxvZ1Ntc2dQcm90b2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Bnet.DialogType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Bnet.DialogArg), global::Bnet.DialogArg.Parser, new[]{ "Text", "Number", "EntityId", "ItemId", "SkillId" }, new[]{ "Value" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bnet.DialogSMSG), global::Bnet.DialogSMSG.Parser, new[]{ "DialogId", "Type", "Args", "SourceEntityId" }, new[]{ "SourceEntityId" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Enums
  public enum DialogType {
    /// <summary>
    /// A plain "read the text and confirm" popup. CHOICE (query the player for an answer) is
    /// planned but out of scope; adding it here plus an interaction id and a repeated choice
    /// list on DialogSMSG is meant to be the whole wire change it needs.
    /// </summary>
    [pbr::OriginalName("CONFIRM")] Confirm = 0,
  }

  #endregion

  #region Messages
  /// <summary>
  ///*
  /// One placeholder value for a dialog text. Typed rather than pre-rendered so that anything
  /// the client already localizes itself (item names, skill names, entity names) stays
  /// localized: the server sends the reference, the client resolves it against its own DBs.
  /// Only use `text` for strings that have no client-side representation at all, e.g. another
  /// player's master name.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DialogArg : pb::IMessage<DialogArg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DialogArg> _parser = new pb::MessageParser<DialogArg>(() => new DialogArg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DialogArg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bnet.DialogSmsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DialogArg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DialogArg(DialogArg other) : this() {
      switch (other.ValueCase) {
        case ValueOneofCase.Text:
          Text = other.Text;
          break;
        case ValueOneofCase.Number:
          Number = other.Number;
          break;
        case ValueOneofCase.EntityId:
          EntityId = other.EntityId;
          break;
        case ValueOneofCase.ItemId:
          ItemId = other.ItemId;
          break;
        case ValueOneofCase.SkillId:
          SkillId = other.SkillId;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DialogArg Clone() {
      return new DialogArg(this);
    }

    /// <summary>Field number for the "text" field.</summary>
    public const int TextFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Text {
      get { return HasText ? (string) value_ : ""; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        valueCase_ = ValueOneofCase.Text;
      }
    }
    /// <summary>Gets whether the "text" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasText {
      get { return valueCase_ == ValueOneofCase.Text; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "text" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearText() {
      if (HasText) {
        ClearValue();
      }
    }

    /// <summary>Field number for the "number" field.</summary>
    public const int NumberFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Number {
      get { return HasNumber ? (long) value_ : 0L; }
      set {
        value_ = value;
        valueCase_ = ValueOneofCase.Number;
      }
    }
    /// <summary>Gets whether the "number" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNumber {
      get { return valueCase_ == ValueOneofCase.Number; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "number" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNumber() {
      if (HasNumber) {
        ClearValue();
      }
    }

    /// <summary>Field number for the "entity_id" field.</summary>
    public const int EntityIdFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong EntityId {
      get { return HasEntityId ? (ulong) value_ : 0UL; }
      set {
        value_ = value;
        valueCase_ = ValueOneofCase.EntityId;
      }
    }
    /// <summary>Gets whether the "entity_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEntityId {
      get { return valueCase_ == ValueOneofCase.EntityId; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "entity_id" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEntityId() {
      if (HasEntityId) {
        ClearValue();
      }
    }

    /// <summary>Field number for the "item_id" field.</summary>
    public const int ItemIdFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ItemId {
      get { return HasItemId ? (long) value_ : 0L; }
      set {
        value_ = value;
        valueCase_ = ValueOneofCase.ItemId;
      }
    }
    /// <summary>Gets whether the "item_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasItemId {
      get { return valueCase_ == ValueOneofCase.ItemId; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "item_id" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearItemId() {
      if (HasItemId) {
        ClearValue();
      }
    }

    /// <summary>Field number for the "skill_id" field.</summary>
    public const int SkillIdFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SkillId {
      get { return HasSkillId ? (long) value_ : 0L; }
      set {
        value_ = value;
        valueCase_ = ValueOneofCase.SkillId;
      }
    }
    /// <summary>Gets whether the "skill_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSkillId {
      get { return valueCase_ == ValueOneofCase.SkillId; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "skill_id" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSkillId() {
      if (HasSkillId) {
        ClearValue();
      }
    }

    private object value_;
    /// <summary>Enum of possible cases for the "value" oneof.</summary>
    public enum ValueOneofCase {
      None = 0,
      Text = 1,
      Number = 2,
      EntityId = 3,
      ItemId = 4,
      SkillId = 5,
    }
    private ValueOneofCase valueCase_ = ValueOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ValueOneofCase ValueCase {
      get { return valueCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearValue() {
      valueCase_ = ValueOneofCase.None;
      value_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DialogArg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DialogArg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Text != other.Text) return false;
      if (Number != other.Number) return false;
      if (EntityId != other.EntityId) return false;
      if (ItemId != other.ItemId) return false;
      if (SkillId != other.SkillId) return false;
      if (ValueCase != other.ValueCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasText) hash ^= Text.GetHashCode();
      if (HasNumber) hash ^= Number.GetHashCode();
      if (HasEntityId) hash ^= EntityId.GetHashCode();
      if (HasItemId) hash ^= ItemId.GetHashCode();
      if (HasSkillId) hash ^= SkillId.GetHashCode();
      hash ^= (int) valueCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasText) {
        output.WriteRawTag(10);
        output.WriteString(Text);
      }
      if (HasNumber) {
        output.WriteRawTag(16);
        output.WriteInt64(Number);
      }
      if (HasEntityId) {
        output.WriteRawTag(24);
        output.WriteUInt64(EntityId);
      }
      if (HasItemId) {
        output.WriteRawTag(32);
        output.WriteInt64(ItemId);
      }
      if (HasSkillId) {
        output.WriteRawTag(40);
        output.WriteInt64(SkillId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasText) {
        output.WriteRawTag(10);
        output.WriteString(Text);
      }
      if (HasNumber) {
        output.WriteRawTag(16);
        output.WriteInt64(Number);
      }
      if (HasEntityId) {
        output.WriteRawTag(24);
        output.WriteUInt64(EntityId);
      }
      if (HasItemId) {
        output.WriteRawTag(32);
        output.WriteInt64(ItemId);
      }
      if (HasSkillId) {
        output.WriteRawTag(40);
        output.WriteInt64(SkillId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasText) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      if (HasNumber) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Number);
      }
      if (HasEntityId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(EntityId);
      }
      if (HasItemId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ItemId);
      }
      if (HasSkillId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SkillId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DialogArg other) {
      if (other == null) {
        return;
      }
      switch (other.ValueCase) {
        case ValueOneofCase.Text:
          Text = other.Text;
          break;
        case ValueOneofCase.Number:
          Number = other.Number;
          break;
        case ValueOneofCase.EntityId:
          EntityId = other.EntityId;
          break;
        case ValueOneofCase.ItemId:
          ItemId = other.ItemId;
          break;
        case ValueOneofCase.SkillId:
          SkillId = other.SkillId;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Text = input.ReadString();
            break;
          }
          case 16: {
            Number = input.ReadInt64();
            break;
          }
          case 24: {
            EntityId = input.ReadUInt64();
            break;
          }
          case 32: {
            ItemId = input.ReadInt64();
            break;
          }
          case 40: {
            SkillId = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Text = input.ReadString();
            break;
          }
          case 16: {
            Number = input.ReadInt64();
            break;
          }
          case 24: {
            EntityId = input.ReadUInt64();
            break;
          }
          case 32: {
            ItemId = input.ReadInt64();
            break;
          }
          case 40: {
            SkillId = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///*
  /// Tells the client to show a dialog. Deliberately carries no text: `dialog_id` is resolved
  /// against the client's `dialogs.csv` translation keys (`DIALOG_&lt;id>_TEXT`, optional
  /// `DIALOG_&lt;id>_TITLE`), the same numeric-id-to-text scheme skill descriptions use.
  ///
  /// This is an account-scoped message, NOT an entity message - it must not be routed through
  /// the client's entity handling. `source_entity_id` is purely informative metadata (who is
  /// speaking, for a portrait or name) and may reference an entity the client does not know.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DialogSMSG : pb::IMessage<DialogSMSG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DialogSMSG> _parser = new pb::MessageParser<DialogSMSG>(() => new DialogSMSG());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DialogSMSG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bnet.DialogSmsgReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DialogSMSG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DialogSMSG(DialogSMSG other) : this() {
      _hasBits0 = other._hasBits0;
      dialogId_ = other.dialogId_;
      type_ = other.type_;
      args_ = other.args_.Clone();
      sourceEntityId_ = other.sourceEntityId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DialogSMSG Clone() {
      return new DialogSMSG(this);
    }

    /// <summary>Field number for the "dialog_id" field.</summary>
    public const int DialogIdFieldNumber = 1;
    private uint dialogId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DialogId {
      get { return dialogId_; }
      set {
        dialogId_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::Bnet.DialogType type_ = global::Bnet.DialogType.Confirm;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bnet.DialogType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "args" field.</summary>
    public const int ArgsFieldNumber = 3;
    private static readonly pbc::MapField<string, global::Bnet.DialogArg>.Codec _map_args_codec
        = new pbc::MapField<string, global::Bnet.DialogArg>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::Bnet.DialogArg.Parser), 26);
    private readonly pbc::MapField<string, global::Bnet.DialogArg> args_ = new pbc::MapField<string, global::Bnet.DialogArg>();
    /// <summary>
    /// Keyed by the placeholder name declared in the server's dialogs.yml, e.g. "masterName"
    /// fills {masterName} in the translated text.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::Bnet.DialogArg> Args {
      get { return args_; }
    }

    /// <summary>Field number for the "source_entity_id" field.</summary>
    public const int SourceEntityIdFieldNumber = 4;
    private readonly static ulong SourceEntityIdDefaultValue = 0UL;

    private ulong sourceEntityId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong SourceEntityId {
      get { if ((_hasBits0 & 1) != 0) { return sourceEntityId_; } else { return SourceEntityIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        sourceEntityId_ = value;
      }
    }
    /// <summary>Gets whether the "source_entity_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSourceEntityId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "source_entity_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSourceEntityId() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DialogSMSG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DialogSMSG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DialogId != other.DialogId) return false;
      if (Type != other.Type) return false;
      if (!Args.Equals(other.Args)) return false;
      if (SourceEntityId != other.SourceEntityId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DialogId != 0) hash ^= DialogId.GetHashCode();
      if (Type != global::Bnet.DialogType.Confirm) hash ^= Type.GetHashCode();
      hash ^= Args.GetHashCode();
      if (HasSourceEntityId) hash ^= SourceEntityId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DialogId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(DialogId);
      }
      if (Type != global::Bnet.DialogType.Confirm) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      args_.WriteTo(output, _map_args_codec);
      if (HasSourceEntityId) {
        output.WriteRawTag(32);
        output.WriteUInt64(SourceEntityId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DialogId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(DialogId);
      }
      if (Type != global::Bnet.DialogType.Confirm) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      args_.WriteTo(ref output, _map_args_codec);
      if (HasSourceEntityId) {
        output.WriteRawTag(32);
        output.WriteUInt64(SourceEntityId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DialogId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DialogId);
      }
      if (Type != global::Bnet.DialogType.Confirm) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      size += args_.CalculateSize(_map_args_codec);
      if (HasSourceEntityId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SourceEntityId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DialogSMSG other) {
      if (other == null) {
        return;
      }
      if (other.DialogId != 0) {
        DialogId = other.DialogId;
      }
      if (other.Type != global::Bnet.DialogType.Confirm) {
        Type = other.Type;
      }
      args_.MergeFrom(other.args_);
      if (other.HasSourceEntityId) {
        SourceEntityId = other.SourceEntityId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DialogId = input.ReadUInt32();
            break;
          }
          case 16: {
            Type = (global::Bnet.DialogType) input.ReadEnum();
            break;
          }
          case 26: {
            args_.AddEntriesFrom(input, _map_args_codec);
            break;
          }
          case 32: {
            SourceEntityId = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DialogId = input.ReadUInt32();
            break;
          }
          case 16: {
            Type = (global::Bnet.DialogType) input.ReadEnum();
            break;
          }
          case 26: {
            args_.AddEntriesFrom(ref input, _map_args_codec);
            break;
          }
          case 32: {
            SourceEntityId = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
