// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages/master/master.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bnet {

  /// <summary>Holder for reflection information generated from messages/master/master.proto</summary>
  public static partial class MasterReflection {

    #region Descriptor
    /// <summary>File descriptor for messages/master/master.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MasterReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxtZXNzYWdlcy9tYXN0ZXIvbWFzdGVyLnByb3RvEgRibmV0GhNtZXNzYWdl",
            "cy92ZWMzLnByb3RvGiFtZXNzYWdlcy9tYXN0ZXIvYmVzdGlhX2luZm8ucHJv",
            "dG8iKAoFQ29sb3ISCQoBchgBIAEoDRIJCgFnGAIgASgNEgkKAWIYAyABKA0i",
            "fwoMRWZmb3J0VmFsdWVzEhAKCHN0cmVuZ3RoGAEgASgNEg8KB2FnaWxpdHkY",
            "AiABKA0SEAoIdml0YWxpdHkYAyABKA0SFAoMaW50ZWxsaWdlbmNlGAQgASgN",
            "EhEKCWRleHRlcml0eRgFIAEoDRIRCgl3aWxscG93ZXIYBiABKA0iqQEKBk1h",
            "c3RlchIiChptYXhfYXZhaWxhYmxlX21hc3Rlcl9zbG90cxgBIAEoDRIiChpt",
            "YXhfYXZhaWxhYmxlX2Jlc3RpYV9zbG90cxgCIAEoDRIgCgZtYXN0ZXIYAyAD",
            "KAsyEC5ibmV0Lk1hc3RlckluZm8SNQoMc3Bhd25fcG9pbnRzGAQgAygLMh8u",
            "Ym5ldC5NYXN0ZXJTcGF3blBvaW50Q2FuZGlkYXRlIk4KGU1hc3RlclNwYXdu",
            "UG9pbnRDYW5kaWRhdGUSCgoCaWQYASABKA0SFwoPc2V0dGxlbWVudF9uYW1l",
            "GAIgASgJEgwKBHRpZXIYAyABKAkilgIKCk1hc3RlckluZm8SEQoJbWFzdGVy",
            "X2lkGAEgASgEEgwKBG5hbWUYAyABKAkSDQoFbGV2ZWwYBCABKA0SHAoIcG9z",
            "aXRpb24YBSABKAsyCi5ibmV0LlZlYzMSHAoEYm9keRgGIAEoDjIOLmJuZXQu",
            "Qm9keVR5cGUSGAoEZmFjZRgHIAEoDjIKLmJuZXQuRmFjZRIfCgpza2luX2Nv",
            "bG9yGAggASgLMgsuYm5ldC5Db2xvchIfCgpoYWlyX2NvbG9yGAkgASgLMgsu",
            "Ym5ldC5Db2xvchIhCgdiZXN0aWFzGAogAygLMhAuYm5ldC5CZXN0aWFJbmZv",
            "Eh0KBGhhaXIYCyABKA4yDy5ibmV0LkhhaXJzdHlsZSoYCghCb2R5VHlwZRIM",
            "CghCT0RZX01fMRAAKhIKBEZhY2USCgoGRkFDRV8xEAAqFwoJSGFpcnN0eWxl",
            "EgoKBkhBSVJfMRAAQiQKFW5ldC5iZXN0aWEuYm5ldC5wcm90b0ILTWFzdGVy",
            "UHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Bnet.Vec3Reflection.Descriptor, global::Bnet.BestiaInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Bnet.BodyType), typeof(global::Bnet.Face), typeof(global::Bnet.Hairstyle), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Bnet.Color), global::Bnet.Color.Parser, new[]{ "R", "G", "B" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bnet.EffortValues), global::Bnet.EffortValues.Parser, new[]{ "Strength", "Agility", "Vitality", "Intelligence", "Dexterity", "Willpower" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bnet.Master), global::Bnet.Master.Parser, new[]{ "MaxAvailableMasterSlots", "MaxAvailableBestiaSlots", "Master_", "SpawnPoints" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bnet.MasterSpawnPointCandidate), global::Bnet.MasterSpawnPointCandidate.Parser, new[]{ "Id", "SettlementName", "Tier" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bnet.MasterInfo), global::Bnet.MasterInfo.Parser, new[]{ "MasterId", "Name", "Level", "Position", "Body", "Face", "SkinColor", "HairColor", "Bestias", "Hair" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum BodyType {
    [pbr::OriginalName("BODY_M_1")] BodyM1 = 0,
  }

  public enum Face {
    [pbr::OriginalName("FACE_1")] _1 = 0,
  }

  public enum Hairstyle {
    [pbr::OriginalName("HAIR_1")] Hair1 = 0,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Color : pb::IMessage<Color>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Color> _parser = new pb::MessageParser<Color>(() => new Color());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Color> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bnet.MasterReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Color() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Color(Color other) : this() {
      r_ = other.r_;
      g_ = other.g_;
      b_ = other.b_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Color Clone() {
      return new Color(this);
    }

    /// <summary>Field number for the "r" field.</summary>
    public const int RFieldNumber = 1;
    private uint r_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint R {
      get { return r_; }
      set {
        r_ = value;
      }
    }

    /// <summary>Field number for the "g" field.</summary>
    public const int GFieldNumber = 2;
    private uint g_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint G {
      get { return g_; }
      set {
        g_ = value;
      }
    }

    /// <summary>Field number for the "b" field.</summary>
    public const int BFieldNumber = 3;
    private uint b_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint B {
      get { return b_; }
      set {
        b_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Color);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Color other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (R != other.R) return false;
      if (G != other.G) return false;
      if (B != other.B) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (R != 0) hash ^= R.GetHashCode();
      if (G != 0) hash ^= G.GetHashCode();
      if (B != 0) hash ^= B.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (R != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(R);
      }
      if (G != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(G);
      }
      if (B != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(B);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (R != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(R);
      }
      if (G != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(G);
      }
      if (B != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(B);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (R != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(R);
      }
      if (G != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(G);
      }
      if (B != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(B);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Color other) {
      if (other == null) {
        return;
      }
      if (other.R != 0) {
        R = other.R;
      }
      if (other.G != 0) {
        G = other.G;
      }
      if (other.B != 0) {
        B = other.B;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            R = input.ReadUInt32();
            break;
          }
          case 16: {
            G = input.ReadUInt32();
            break;
          }
          case 24: {
            B = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            R = input.ReadUInt32();
            break;
          }
          case 16: {
            G = input.ReadUInt32();
            break;
          }
          case 24: {
            B = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///*
  /// A master's six effort values - the player-controlled part of their status values. Field order
  /// follows the StatusAttribute enum in invest_status_point_cmsg.proto.
  ///
  /// At creation every value starts at 1 and the player distributes a fixed budget across them under an
  /// escalating cost curve; the server re-validates the distribution and refuses anything that does not
  /// spend it exactly. See https://docs.bestia-game.net/docs/mechanics/statusvalues/#effort-values
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EffortValues : pb::IMessage<EffortValues>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EffortValues> _parser = new pb::MessageParser<EffortValues>(() => new EffortValues());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EffortValues> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bnet.MasterReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EffortValues() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EffortValues(EffortValues other) : this() {
      strength_ = other.strength_;
      agility_ = other.agility_;
      vitality_ = other.vitality_;
      intelligence_ = other.intelligence_;
      dexterity_ = other.dexterity_;
      willpower_ = other.willpower_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EffortValues Clone() {
      return new EffortValues(this);
    }

    /// <summary>Field number for the "strength" field.</summary>
    public const int StrengthFieldNumber = 1;
    private uint strength_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Strength {
      get { return strength_; }
      set {
        strength_ = value;
      }
    }

    /// <summary>Field number for the "agility" field.</summary>
    public const int AgilityFieldNumber = 2;
    private uint agility_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Agility {
      get { return agility_; }
      set {
        agility_ = value;
      }
    }

    /// <summary>Field number for the "vitality" field.</summary>
    public const int VitalityFieldNumber = 3;
    private uint vitality_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Vitality {
      get { return vitality_; }
      set {
        vitality_ = value;
      }
    }

    /// <summary>Field number for the "intelligence" field.</summary>
    public const int IntelligenceFieldNumber = 4;
    private uint intelligence_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Intelligence {
      get { return intelligence_; }
      set {
        intelligence_ = value;
      }
    }

    /// <summary>Field number for the "dexterity" field.</summary>
    public const int DexterityFieldNumber = 5;
    private uint dexterity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Dexterity {
      get { return dexterity_; }
      set {
        dexterity_ = value;
      }
    }

    /// <summary>Field number for the "willpower" field.</summary>
    public const int WillpowerFieldNumber = 6;
    private uint willpower_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Willpower {
      get { return willpower_; }
      set {
        willpower_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EffortValues);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EffortValues other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Strength != other.Strength) return false;
      if (Agility != other.Agility) return false;
      if (Vitality != other.Vitality) return false;
      if (Intelligence != other.Intelligence) return false;
      if (Dexterity != other.Dexterity) return false;
      if (Willpower != other.Willpower) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Strength != 0) hash ^= Strength.GetHashCode();
      if (Agility != 0) hash ^= Agility.GetHashCode();
      if (Vitality != 0) hash ^= Vitality.GetHashCode();
      if (Intelligence != 0) hash ^= Intelligence.GetHashCode();
      if (Dexterity != 0) hash ^= Dexterity.GetHashCode();
      if (Willpower != 0) hash ^= Willpower.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Strength != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Strength);
      }
      if (Agility != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Agility);
      }
      if (Vitality != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Vitality);
      }
      if (Intelligence != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Intelligence);
      }
      if (Dexterity != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Dexterity);
      }
      if (Willpower != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Willpower);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Strength != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Strength);
      }
      if (Agility != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Agility);
      }
      if (Vitality != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Vitality);
      }
      if (Intelligence != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Intelligence);
      }
      if (Dexterity != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Dexterity);
      }
      if (Willpower != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Willpower);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Strength != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Strength);
      }
      if (Agility != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Agility);
      }
      if (Vitality != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Vitality);
      }
      if (Intelligence != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Intelligence);
      }
      if (Dexterity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Dexterity);
      }
      if (Willpower != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Willpower);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EffortValues other) {
      if (other == null) {
        return;
      }
      if (other.Strength != 0) {
        Strength = other.Strength;
      }
      if (other.Agility != 0) {
        Agility = other.Agility;
      }
      if (other.Vitality != 0) {
        Vitality = other.Vitality;
      }
      if (other.Intelligence != 0) {
        Intelligence = other.Intelligence;
      }
      if (other.Dexterity != 0) {
        Dexterity = other.Dexterity;
      }
      if (other.Willpower != 0) {
        Willpower = other.Willpower;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Strength = input.ReadUInt32();
            break;
          }
          case 16: {
            Agility = input.ReadUInt32();
            break;
          }
          case 24: {
            Vitality = input.ReadUInt32();
            break;
          }
          case 32: {
            Intelligence = input.ReadUInt32();
            break;
          }
          case 40: {
            Dexterity = input.ReadUInt32();
            break;
          }
          case 48: {
            Willpower = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Strength = input.ReadUInt32();
            break;
          }
          case 16: {
            Agility = input.ReadUInt32();
            break;
          }
          case 24: {
            Vitality = input.ReadUInt32();
            break;
          }
          case 32: {
            Intelligence = input.ReadUInt32();
            break;
          }
          case 40: {
            Dexterity = input.ReadUInt32();
            break;
          }
          case 48: {
            Willpower = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///*
  /// A list of all available master.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Master : pb::IMessage<Master>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Master> _parser = new pb::MessageParser<Master>(() => new Master());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Master> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bnet.MasterReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Master() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Master(Master other) : this() {
      maxAvailableMasterSlots_ = other.maxAvailableMasterSlots_;
      maxAvailableBestiaSlots_ = other.maxAvailableBestiaSlots_;
      master_ = other.master_.Clone();
      spawnPoints_ = other.spawnPoints_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Master Clone() {
      return new Master(this);
    }

    /// <summary>Field number for the "max_available_master_slots" field.</summary>
    public const int MaxAvailableMasterSlotsFieldNumber = 1;
    private uint maxAvailableMasterSlots_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MaxAvailableMasterSlots {
      get { return maxAvailableMasterSlots_; }
      set {
        maxAvailableMasterSlots_ = value;
      }
    }

    /// <summary>Field number for the "max_available_bestia_slots" field.</summary>
    public const int MaxAvailableBestiaSlotsFieldNumber = 2;
    private uint maxAvailableBestiaSlots_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MaxAvailableBestiaSlots {
      get { return maxAvailableBestiaSlots_; }
      set {
        maxAvailableBestiaSlots_ = value;
      }
    }

    /// <summary>Field number for the "master" field.</summary>
    public const int Master_FieldNumber = 3;
    private static readonly pb::FieldCodec<global::Bnet.MasterInfo> _repeated_master_codec
        = pb::FieldCodec.ForMessage(26, global::Bnet.MasterInfo.Parser);
    private readonly pbc::RepeatedField<global::Bnet.MasterInfo> master_ = new pbc::RepeatedField<global::Bnet.MasterInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Bnet.MasterInfo> Master_ {
      get { return master_; }
    }

    /// <summary>Field number for the "spawn_points" field.</summary>
    public const int SpawnPointsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Bnet.MasterSpawnPointCandidate> _repeated_spawnPoints_codec
        = pb::FieldCodec.ForMessage(34, global::Bnet.MasterSpawnPointCandidate.Parser);
    private readonly pbc::RepeatedField<global::Bnet.MasterSpawnPointCandidate> spawnPoints_ = new pbc::RepeatedField<global::Bnet.MasterSpawnPointCandidate>();
    /// <summary>
    /// Settlement spawn point candidates a new master can choose to start life near. Populated
    /// regardless of whether the account has any free master slots, so the creation screen has them
    /// ready the moment the player picks an empty slot.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Bnet.MasterSpawnPointCandidate> SpawnPoints {
      get { return spawnPoints_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Master);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Master other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MaxAvailableMasterSlots != other.MaxAvailableMasterSlots) return false;
      if (MaxAvailableBestiaSlots != other.MaxAvailableBestiaSlots) return false;
      if(!master_.Equals(other.master_)) return false;
      if(!spawnPoints_.Equals(other.spawnPoints_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MaxAvailableMasterSlots != 0) hash ^= MaxAvailableMasterSlots.GetHashCode();
      if (MaxAvailableBestiaSlots != 0) hash ^= MaxAvailableBestiaSlots.GetHashCode();
      hash ^= master_.GetHashCode();
      hash ^= spawnPoints_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MaxAvailableMasterSlots != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MaxAvailableMasterSlots);
      }
      if (MaxAvailableBestiaSlots != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(MaxAvailableBestiaSlots);
      }
      master_.WriteTo(output, _repeated_master_codec);
      spawnPoints_.WriteTo(output, _repeated_spawnPoints_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MaxAvailableMasterSlots != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MaxAvailableMasterSlots);
      }
      if (MaxAvailableBestiaSlots != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(MaxAvailableBestiaSlots);
      }
      master_.WriteTo(ref output, _repeated_master_codec);
      spawnPoints_.WriteTo(ref output, _repeated_spawnPoints_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MaxAvailableMasterSlots != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MaxAvailableMasterSlots);
      }
      if (MaxAvailableBestiaSlots != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MaxAvailableBestiaSlots);
      }
      size += master_.CalculateSize(_repeated_master_codec);
      size += spawnPoints_.CalculateSize(_repeated_spawnPoints_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Master other) {
      if (other == null) {
        return;
      }
      if (other.MaxAvailableMasterSlots != 0) {
        MaxAvailableMasterSlots = other.MaxAvailableMasterSlots;
      }
      if (other.MaxAvailableBestiaSlots != 0) {
        MaxAvailableBestiaSlots = other.MaxAvailableBestiaSlots;
      }
      master_.Add(other.master_);
      spawnPoints_.Add(other.spawnPoints_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MaxAvailableMasterSlots = input.ReadUInt32();
            break;
          }
          case 16: {
            MaxAvailableBestiaSlots = input.ReadUInt32();
            break;
          }
          case 26: {
            master_.AddEntriesFrom(input, _repeated_master_codec);
            break;
          }
          case 34: {
            spawnPoints_.AddEntriesFrom(input, _repeated_spawnPoints_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MaxAvailableMasterSlots = input.ReadUInt32();
            break;
          }
          case 16: {
            MaxAvailableBestiaSlots = input.ReadUInt32();
            break;
          }
          case 26: {
            master_.AddEntriesFrom(ref input, _repeated_master_codec);
            break;
          }
          case 34: {
            spawnPoints_.AddEntriesFrom(ref input, _repeated_spawnPoints_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///*
  /// One settlement a new master could choose to start life near.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MasterSpawnPointCandidate : pb::IMessage<MasterSpawnPointCandidate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MasterSpawnPointCandidate> _parser = new pb::MessageParser<MasterSpawnPointCandidate>(() => new MasterSpawnPointCandidate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MasterSpawnPointCandidate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bnet.MasterReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MasterSpawnPointCandidate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MasterSpawnPointCandidate(MasterSpawnPointCandidate other) : this() {
      id_ = other.id_;
      settlementName_ = other.settlementName_;
      tier_ = other.tier_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MasterSpawnPointCandidate Clone() {
      return new MasterSpawnPointCandidate(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private uint id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "settlement_name" field.</summary>
    public const int SettlementNameFieldNumber = 2;
    private string settlementName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SettlementName {
      get { return settlementName_; }
      set {
        settlementName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tier" field.</summary>
    public const int TierFieldNumber = 3;
    private string tier_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Tier {
      get { return tier_; }
      set {
        tier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MasterSpawnPointCandidate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MasterSpawnPointCandidate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (SettlementName != other.SettlementName) return false;
      if (Tier != other.Tier) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (SettlementName.Length != 0) hash ^= SettlementName.GetHashCode();
      if (Tier.Length != 0) hash ^= Tier.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (SettlementName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SettlementName);
      }
      if (Tier.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Tier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (SettlementName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SettlementName);
      }
      if (Tier.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Tier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
      }
      if (SettlementName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SettlementName);
      }
      if (Tier.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Tier);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MasterSpawnPointCandidate other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.SettlementName.Length != 0) {
        SettlementName = other.SettlementName;
      }
      if (other.Tier.Length != 0) {
        Tier = other.Tier;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 18: {
            SettlementName = input.ReadString();
            break;
          }
          case 26: {
            Tier = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 18: {
            SettlementName = input.ReadString();
            break;
          }
          case 26: {
            Tier = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MasterInfo : pb::IMessage<MasterInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MasterInfo> _parser = new pb::MessageParser<MasterInfo>(() => new MasterInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MasterInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bnet.MasterReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MasterInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MasterInfo(MasterInfo other) : this() {
      masterId_ = other.masterId_;
      name_ = other.name_;
      level_ = other.level_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      body_ = other.body_;
      face_ = other.face_;
      skinColor_ = other.skinColor_ != null ? other.skinColor_.Clone() : null;
      hairColor_ = other.hairColor_ != null ? other.hairColor_.Clone() : null;
      bestias_ = other.bestias_.Clone();
      hair_ = other.hair_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MasterInfo Clone() {
      return new MasterInfo(this);
    }

    /// <summary>Field number for the "master_id" field.</summary>
    public const int MasterIdFieldNumber = 1;
    private ulong masterId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong MasterId {
      get { return masterId_; }
      set {
        masterId_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 4;
    private uint level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 5;
    private global::Bnet.Vec3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bnet.Vec3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "body" field.</summary>
    public const int BodyFieldNumber = 6;
    private global::Bnet.BodyType body_ = global::Bnet.BodyType.BodyM1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bnet.BodyType Body {
      get { return body_; }
      set {
        body_ = value;
      }
    }

    /// <summary>Field number for the "face" field.</summary>
    public const int FaceFieldNumber = 7;
    private global::Bnet.Face face_ = global::Bnet.Face._1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bnet.Face Face {
      get { return face_; }
      set {
        face_ = value;
      }
    }

    /// <summary>Field number for the "skin_color" field.</summary>
    public const int SkinColorFieldNumber = 8;
    private global::Bnet.Color skinColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bnet.Color SkinColor {
      get { return skinColor_; }
      set {
        skinColor_ = value;
      }
    }

    /// <summary>Field number for the "hair_color" field.</summary>
    public const int HairColorFieldNumber = 9;
    private global::Bnet.Color hairColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bnet.Color HairColor {
      get { return hairColor_; }
      set {
        hairColor_ = value;
      }
    }

    /// <summary>Field number for the "bestias" field.</summary>
    public const int BestiasFieldNumber = 10;
    private static readonly pb::FieldCodec<global::Bnet.BestiaInfo> _repeated_bestias_codec
        = pb::FieldCodec.ForMessage(82, global::Bnet.BestiaInfo.Parser);
    private readonly pbc::RepeatedField<global::Bnet.BestiaInfo> bestias_ = new pbc::RepeatedField<global::Bnet.BestiaInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Bnet.BestiaInfo> Bestias {
      get { return bestias_; }
    }

    /// <summary>Field number for the "hair" field.</summary>
    public const int HairFieldNumber = 11;
    private global::Bnet.Hairstyle hair_ = global::Bnet.Hairstyle.Hair1;
    /// <summary>
    /// TODO add an equipment list
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bnet.Hairstyle Hair {
      get { return hair_; }
      set {
        hair_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MasterInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MasterInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MasterId != other.MasterId) return false;
      if (Name != other.Name) return false;
      if (Level != other.Level) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (Body != other.Body) return false;
      if (Face != other.Face) return false;
      if (!object.Equals(SkinColor, other.SkinColor)) return false;
      if (!object.Equals(HairColor, other.HairColor)) return false;
      if(!bestias_.Equals(other.bestias_)) return false;
      if (Hair != other.Hair) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MasterId != 0UL) hash ^= MasterId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (Body != global::Bnet.BodyType.BodyM1) hash ^= Body.GetHashCode();
      if (Face != global::Bnet.Face._1) hash ^= Face.GetHashCode();
      if (skinColor_ != null) hash ^= SkinColor.GetHashCode();
      if (hairColor_ != null) hash ^= HairColor.GetHashCode();
      hash ^= bestias_.GetHashCode();
      if (Hair != global::Bnet.Hairstyle.Hair1) hash ^= Hair.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MasterId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(MasterId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (Level != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Level);
      }
      if (position_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Position);
      }
      if (Body != global::Bnet.BodyType.BodyM1) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Body);
      }
      if (Face != global::Bnet.Face._1) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Face);
      }
      if (skinColor_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(SkinColor);
      }
      if (hairColor_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(HairColor);
      }
      bestias_.WriteTo(output, _repeated_bestias_codec);
      if (Hair != global::Bnet.Hairstyle.Hair1) {
        output.WriteRawTag(88);
        output.WriteEnum((int) Hair);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MasterId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(MasterId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (Level != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Level);
      }
      if (position_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Position);
      }
      if (Body != global::Bnet.BodyType.BodyM1) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Body);
      }
      if (Face != global::Bnet.Face._1) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Face);
      }
      if (skinColor_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(SkinColor);
      }
      if (hairColor_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(HairColor);
      }
      bestias_.WriteTo(ref output, _repeated_bestias_codec);
      if (Hair != global::Bnet.Hairstyle.Hair1) {
        output.WriteRawTag(88);
        output.WriteEnum((int) Hair);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MasterId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MasterId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Level);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (Body != global::Bnet.BodyType.BodyM1) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Body);
      }
      if (Face != global::Bnet.Face._1) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Face);
      }
      if (skinColor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SkinColor);
      }
      if (hairColor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HairColor);
      }
      size += bestias_.CalculateSize(_repeated_bestias_codec);
      if (Hair != global::Bnet.Hairstyle.Hair1) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Hair);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MasterInfo other) {
      if (other == null) {
        return;
      }
      if (other.MasterId != 0UL) {
        MasterId = other.MasterId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Bnet.Vec3();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.Body != global::Bnet.BodyType.BodyM1) {
        Body = other.Body;
      }
      if (other.Face != global::Bnet.Face._1) {
        Face = other.Face;
      }
      if (other.skinColor_ != null) {
        if (skinColor_ == null) {
          SkinColor = new global::Bnet.Color();
        }
        SkinColor.MergeFrom(other.SkinColor);
      }
      if (other.hairColor_ != null) {
        if (hairColor_ == null) {
          HairColor = new global::Bnet.Color();
        }
        HairColor.MergeFrom(other.HairColor);
      }
      bestias_.Add(other.bestias_);
      if (other.Hair != global::Bnet.Hairstyle.Hair1) {
        Hair = other.Hair;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MasterId = input.ReadUInt64();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 32: {
            Level = input.ReadUInt32();
            break;
          }
          case 42: {
            if (position_ == null) {
              Position = new global::Bnet.Vec3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 48: {
            Body = (global::Bnet.BodyType) input.ReadEnum();
            break;
          }
          case 56: {
            Face = (global::Bnet.Face) input.ReadEnum();
            break;
          }
          case 66: {
            if (skinColor_ == null) {
              SkinColor = new global::Bnet.Color();
            }
            input.ReadMessage(SkinColor);
            break;
          }
          case 74: {
            if (hairColor_ == null) {
              HairColor = new global::Bnet.Color();
            }
            input.ReadMessage(HairColor);
            break;
          }
          case 82: {
            bestias_.AddEntriesFrom(input, _repeated_bestias_codec);
            break;
          }
          case 88: {
            Hair = (global::Bnet.Hairstyle) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MasterId = input.ReadUInt64();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 32: {
            Level = input.ReadUInt32();
            break;
          }
          case 42: {
            if (position_ == null) {
              Position = new global::Bnet.Vec3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 48: {
            Body = (global::Bnet.BodyType) input.ReadEnum();
            break;
          }
          case 56: {
            Face = (global::Bnet.Face) input.ReadEnum();
            break;
          }
          case 66: {
            if (skinColor_ == null) {
              SkinColor = new global::Bnet.Color();
            }
            input.ReadMessage(SkinColor);
            break;
          }
          case 74: {
            if (hairColor_ == null) {
              HairColor = new global::Bnet.Color();
            }
            input.ReadMessage(HairColor);
            break;
          }
          case 82: {
            bestias_.AddEntriesFrom(ref input, _repeated_bestias_codec);
            break;
          }
          case 88: {
            Hair = (global::Bnet.Hairstyle) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
