// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages/system/operation_error.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bnet {

  /// <summary>Holder for reflection information generated from messages/system/operation_error.proto</summary>
  public static partial class OperationErrorReflection {

    #region Descriptor
    /// <summary>File descriptor for messages/system/operation_error.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OperationErrorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVtZXNzYWdlcy9zeXN0ZW0vb3BlcmF0aW9uX2Vycm9yLnByb3RvEgRibmV0",
            "IjsKDk9wZXJhdGlvbkVycm9yEhsKBGNvZGUYASABKA4yDS5ibmV0Lk9wRXJy",
            "b3ISDAoEYXJncxgCIAMoCSqVCAoHT3BFcnJvchIdChlNQVNURVJfTkFNRV9B",
            "TFJFQURZX1RBS0VOEAASHgoaTUFTVEVSX01BWF9NQVNURVJTX1JFQUNIRUQQ",
            "ARIXChNNQVNURVJfSU5WQUxJRF9OQU1FEAISGAoUTUFTVEVSX0dFTkVSQUxf",
            "RVJST1IQAxIcChhFUVVJUF9TTE9UX05PVF9BVkFJTEFCTEUQBBIYChRFUVVJ",
            "UF9JVEVNX05PVF9GT1VORBAFEhUKEUVRVUlQX05PVF9BTExPV0VEEAYSHgoa",
            "TUFTVEVSX0lOVkFMSURfU1BBV05fUE9JTlQQBxIeChpBSV9DT05GSUdfQkVT",
            "VElBX05PVF9PV05FRBAIEhwKGEFJX0NPTkZJR19JTlZBTElEX1NUQU5DRRAJ",
            "EhQKEE1BU1RFUl9OT1RfT1dORUQQChIYChRNQVNURVJfTkFNRV9NSVNNQVRD",
            "SBALEhEKDU1BU1RFUl9JTl9VU0UQDBIXChNDT0xMRUNUX1RBUkdFVF9HT05F",
            "EA0SGAoUQ09MTEVDVF9PVVRfT0ZfUkFOR0UQDhIbChdDT0xMRUNUX05PVF9D",
            "T0xMRUNUSUJMRRAPEhYKEkNSQUZUX05PVF9QT1NTSUJMRRAQEhsKF0NSQUZU",
            "X01JU1NJTkdfTUFURVJJQUxTEBESHQoZQ1JBRlRfQUxSRUFEWV9JTl9QUk9H",
            "UkVTUxASEhAKDENSQUZUX0ZBSUxFRBATEhgKFENSQUZUX0lURU1fREVTVFJP",
            "WUVEEBQSFQoRU1RSVUNUVVJFX05PX1JPT00QFRIbChdCQVNJQ19TS0lMTF9D",
            "SEFUX0xPQ0tFRBAWEhwKGEJBU0lDX1NLSUxMX1BBUlRZX0xPQ0tFRBAXEhsK",
            "F0NSQUZUX0lURU1fVE9PX0FEVkFOQ0VEEBgSFwoTRVFVSVBfTEVWRUxfVE9P",
            "X0xPVxAZEhMKD0NIQVJUX05PVF9GT1VORBAaEhUKEUNIQVJUX05FRURTX0JM",
            "QU5LEBsSFAoQQ0hBUlRfTUVSR0VfU0FNRRAcEhUKEUNIQVJUX1NUQUxFX1dP",
            "UkxEEB0SHAoYVFJBREVfVEFSR0VUX1VOQVZBSUxBQkxFEB4SFgoSVFJBREVf",
            "T1VUX09GX1JBTkdFEB8SEgoOVFJBREVfREVDTElORUQQIBITCg9UUkFERV9D",
            "QU5DRUxMRUQQIRIVChFUUkFERV9XQUxLRURfQVdBWRAiEhAKDFRSQURFX0ZB",
            "SUxFRBAjEhwKGEJBU0lDX1NLSUxMX1RSQURFX0xPQ0tFRBAkEh4KGkNIQVRf",
            "Q09NTUFORF9OT19QRVJNSVNTSU9OECUSGAoUQ0hBVF9DT01NQU5EX1VOS05P",
            "V04QJhIXChNDSEFUX0NPTU1BTkRfRkFJTEVEECdCLAoVbmV0LmJlc3RpYS5i",
            "bmV0LnByb3RvQhNPcGVyYXRpb25FcnJvclByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Bnet.OpError), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Bnet.OperationError), global::Bnet.OperationError.Parser, new[]{ "Code", "Args" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum OpError {
    [pbr::OriginalName("MASTER_NAME_ALREADY_TAKEN")] MasterNameAlreadyTaken = 0,
    [pbr::OriginalName("MASTER_MAX_MASTERS_REACHED")] MasterMaxMastersReached = 1,
    [pbr::OriginalName("MASTER_INVALID_NAME")] MasterInvalidName = 2,
    [pbr::OriginalName("MASTER_GENERAL_ERROR")] MasterGeneralError = 3,
    [pbr::OriginalName("EQUIP_SLOT_NOT_AVAILABLE")] EquipSlotNotAvailable = 4,
    [pbr::OriginalName("EQUIP_ITEM_NOT_FOUND")] EquipItemNotFound = 5,
    [pbr::OriginalName("EQUIP_NOT_ALLOWED")] EquipNotAllowed = 6,
    [pbr::OriginalName("MASTER_INVALID_SPAWN_POINT")] MasterInvalidSpawnPoint = 7,
    [pbr::OriginalName("AI_CONFIG_BESTIA_NOT_OWNED")] AiConfigBestiaNotOwned = 8,
    [pbr::OriginalName("AI_CONFIG_INVALID_STANCE")] AiConfigInvalidStance = 9,
    /// <summary>
    /// Also answers "no such master": a client must not be able to tell an id that does not exist from
    /// one that belongs to somebody else, or deleting becomes a way to probe for foreign master ids.
    /// </summary>
    [pbr::OriginalName("MASTER_NOT_OWNED")] MasterNotOwned = 10,
    /// <summary>
    /// The name typed into the delete confirmation does not match the master's.
    /// </summary>
    [pbr::OriginalName("MASTER_NAME_MISMATCH")] MasterNameMismatch = 11,
    /// <summary>
    /// The master is still live in the world (selected, or not finished writing itself back after a logout).
    /// </summary>
    [pbr::OriginalName("MASTER_IN_USE")] MasterInUse = 12,
    /// <summary>
    /// The prop is not there to be taken: never was, already collected by someone else, felled by the attack
    /// path, or its column was re-materialised under a client still holding the old id. Deliberately one code
    /// for all four, on the same reasoning as MASTER_NOT_OWNED above - the ids are ephemeral, and letting a
    /// client tell "taken" from "never existed" would make them a way to probe what stands on ground it is not
    /// holding.
    /// </summary>
    [pbr::OriginalName("COLLECT_TARGET_GONE")] CollectTargetGone = 13,
    /// <summary>
    /// Too far away. The one refusal a player can actually act on, which is why it is not folded into the code
    /// above; the client walks into range before sending, so this should only be reachable under latency.
    /// </summary>
    [pbr::OriginalName("COLLECT_OUT_OF_RANGE")] CollectOutOfRange = 14,
    /// <summary>
    /// The client offered a click on a kind that prop-kinds.yml gives no `collect` block. Not reachable by a
    /// player - it means PropAppearance's Collectible mirror has drifted from the server, and it is kept
    /// separate precisely so that drift is nameable rather than hidden inside COLLECT_TARGET_GONE.
    /// </summary>
    [pbr::OriginalName("COLLECT_NOT_COLLECTIBLE")] CollectNotCollectible = 15,
    /// <summary>
    /// Crafting. The first three are refusals - the craft never started - and the last two are outcomes: the
    /// materials are gone either way, which is the whole risk in a craft and has to be visible.
    ///
    /// Deliberately one code for "you cannot do this recipe" whatever the reason (unknown recipe, skill too
    /// low, no station in range, target not held, target is a plain stack, nothing left to repair). A client
    /// that could tell those apart would be a way to enumerate the recipe catalogue and other players' items,
    /// and the crafting window already knows all of it except the target check.
    /// </summary>
    [pbr::OriginalName("CRAFT_NOT_POSSIBLE")] CraftNotPossible = 16,
    [pbr::OriginalName("CRAFT_MISSING_MATERIALS")] CraftMissingMaterials = 17,
    [pbr::OriginalName("CRAFT_ALREADY_IN_PROGRESS")] CraftAlreadyInProgress = 18,
    [pbr::OriginalName("CRAFT_FAILED")] CraftFailed = 19,
    /// <summary>
    /// A failed rune-slot cut took the item with it - see MasterCraftBonusService.destroyChance.
    /// </summary>
    [pbr::OriginalName("CRAFT_ITEM_DESTROYED")] CraftItemDestroyed = 20,
    /// <summary>
    /// Placing a crafting station: no room, or already standing on somebody else's.
    /// </summary>
    [pbr::OriginalName("STRUCTURE_NO_ROOM")] StructureNoRoom = 21,
    /// <summary>
    /// Basic Skill gates what a player may do at all - see net.bestia.zone.account.master.skill.BasicSkillGate.
    /// A code per subsystem rather than one shared code, because the ranks differ and the client says which rank
    /// is needed. Trade posts and sitting are still unbuilt, so ranks 3 and 4 have nothing here.
    /// </summary>
    [pbr::OriginalName("BASIC_SKILL_CHAT_LOCKED")] BasicSkillChatLocked = 22,
    [pbr::OriginalName("BASIC_SKILL_PARTY_LOCKED")] BasicSkillPartyLocked = 23,
    /// <summary>
    /// The item is of a higher tier than the crafter can reach - see MasterCraftBonusService.maxItemLevel. Kept
    /// apart from CRAFT_NOT_POSSIBLE because it is the one crafting refusal a player can act on by investing:
    /// "raise the skill" is useful, and folding it into the catch-all would have hidden it.
    /// </summary>
    [pbr::OriginalName("CRAFT_ITEM_TOO_ADVANCED")] CraftItemTooAdvanced = 24,
    /// <summary>
    /// The wearer is below the item's level - see Item.level.
    /// </summary>
    [pbr::OriginalName("EQUIP_LEVEL_TOO_LOW")] EquipLevelTooLow = 25,
    /// <summary>
    /// Charts. The chart named is not held, not a chart at all, or the templates are missing from items.yml -
    /// one code for all three on the reasoning MASTER_NOT_OWNED gives: a client that could tell them apart
    /// would be a way to probe what other players are carrying.
    /// </summary>
    [pbr::OriginalName("CHART_NOT_FOUND")] ChartNotFound = 26,
    /// <summary>
    /// Surveying and copying both consume a blank chart, and there is none in the inventory.
    /// </summary>
    [pbr::OriginalName("CHART_NEEDS_BLANK")] ChartNeedsBlank = 27,
    /// <summary>
    /// A chart cannot be merged into itself. Reachable only from a hand-built client - the map window picks two
    /// rows - but the alternative would be silently consuming the chart into itself.
    /// </summary>
    [pbr::OriginalName("CHART_MERGE_SAME")] ChartMergeSame = 28,
    /// <summary>
    /// The chart was surveyed in a world that has since been regenerated, so its coverage names ground that no
    /// longer exists. Named rather than folded into CHART_NOT_FOUND because the player still has the item and
    /// would otherwise be told it does not exist.
    /// </summary>
    [pbr::OriginalName("CHART_STALE_WORLD")] ChartStaleWorld = 29,
    /// <summary>
    /// Trading. Deliberately one code for every reason the other side cannot be traded with - not a player,
    /// offline, already trading, gone, or the request sat unanswered until it expired. On the same reasoning
    /// MASTER_NOT_OWNED gives: a client that could tell those apart would be a way to probe who is online and
    /// what they are busy with.
    /// </summary>
    [pbr::OriginalName("TRADE_TARGET_UNAVAILABLE")] TradeTargetUnavailable = 30,
    /// <summary>
    /// Too far away to ask. The one refusal a player can act on, which is why it is not folded into the code
    /// above; the client only offers Trade on somebody in range, so this should only be reachable under latency.
    /// </summary>
    [pbr::OriginalName("TRADE_OUT_OF_RANGE")] TradeOutOfRange = 31,
    /// <summary>
    /// The three ways a trade ends that are somebody else's doing, so the player is told who. Each carries the
    /// other party's master name in args[0].
    /// </summary>
    [pbr::OriginalName("TRADE_DECLINED")] TradeDeclined = 32,
    [pbr::OriginalName("TRADE_CANCELLED")] TradeCancelled = 33,
    [pbr::OriginalName("TRADE_WALKED_AWAY")] TradeWalkedAway = 34,
    /// <summary>
    /// The exchange itself could not be committed and was rolled back whole - nothing changed hands. Not
    /// reachable by a player: it means the reserved items moved under the transaction, and both sides get it.
    /// </summary>
    [pbr::OriginalName("TRADE_FAILED")] TradeFailed = 35,
    [pbr::OriginalName("BASIC_SKILL_TRADE_LOCKED")] BasicSkillTradeLocked = 36,
    /// <summary>
    /// Chat commands. A command the player may not use is told apart from one that does not exist, because the
    /// two are different problems: the first is answered by asking a GM, the second by checking the spelling.
    /// The distinction leaks that a command exists, which is fine - `/help` lists them and they are not secret.
    /// </summary>
    [pbr::OriginalName("CHAT_COMMAND_NO_PERMISSION")] ChatCommandNoPermission = 37,
    [pbr::OriginalName("CHAT_COMMAND_UNKNOWN")] ChatCommandUnknown = 38,
    /// <summary>
    /// The command matched and then threw. Not reachable by typing: the grammar already rejected the bad forms,
    /// so this means the command itself is broken, and the stack trace is server-side.
    /// </summary>
    [pbr::OriginalName("CHAT_COMMAND_FAILED")] ChatCommandFailed = 39,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OperationError : pb::IMessage<OperationError>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OperationError> _parser = new pb::MessageParser<OperationError>(() => new OperationError());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OperationError> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bnet.OperationErrorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OperationError() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OperationError(OperationError other) : this() {
      code_ = other.code_;
      args_ = other.args_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OperationError Clone() {
      return new OperationError(this);
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 1;
    private global::Bnet.OpError code_ = global::Bnet.OpError.MasterNameAlreadyTaken;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bnet.OpError Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "args" field.</summary>
    public const int ArgsFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_args_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> args_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// Substitution values for the client's message template, in order - a player's name, a count, a place.
    /// Never a server-composed sentence: the wording and its translation stay on the client, which is what
    /// keeps a code from quietly becoming an English string on the wire. Most codes carry none.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Args {
      get { return args_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OperationError);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OperationError other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if(!args_.Equals(other.args_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != global::Bnet.OpError.MasterNameAlreadyTaken) hash ^= Code.GetHashCode();
      hash ^= args_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Code != global::Bnet.OpError.MasterNameAlreadyTaken) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Code);
      }
      args_.WriteTo(output, _repeated_args_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Code != global::Bnet.OpError.MasterNameAlreadyTaken) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Code);
      }
      args_.WriteTo(ref output, _repeated_args_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Code != global::Bnet.OpError.MasterNameAlreadyTaken) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Code);
      }
      size += args_.CalculateSize(_repeated_args_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OperationError other) {
      if (other == null) {
        return;
      }
      if (other.Code != global::Bnet.OpError.MasterNameAlreadyTaken) {
        Code = other.Code;
      }
      args_.Add(other.args_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = (global::Bnet.OpError) input.ReadEnum();
            break;
          }
          case 18: {
            args_.AddEntriesFrom(input, _repeated_args_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Code = (global::Bnet.OpError) input.ReadEnum();
            break;
          }
          case 18: {
            args_.AddEntriesFrom(ref input, _repeated_args_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
