// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages/party/party_info_smsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bnet {

  /// <summary>Holder for reflection information generated from messages/party/party_info_smsg.proto</summary>
  public static partial class PartyInfoSmsgReflection {

    #region Descriptor
    /// <summary>File descriptor for messages/party/party_info_smsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PartyInfoSmsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRtZXNzYWdlcy9wYXJ0eS9wYXJ0eV9pbmZvX3Ntc2cucHJvdG8SBGJuZXQa",
            "E21lc3NhZ2VzL3ZlYzMucHJvdG8iWAoNUGFydHlJbmZvU01TRxIQCghwYXJ0",
            "eV9pZBgBIAEoBBISCgpwYXJ0eV9uYW1lGAIgASgJEiEKBm1lbWJlchgDIAMo",
            "CzIRLmJuZXQuUGFydHlNZW1iZXIiaQoLUGFydHlNZW1iZXISEwoLbWFzdGVy",
            "X25hbWUYASABKAkSNQoLb25saW5lX2RhdGEYAiABKAsyGy5ibmV0LlBhcnR5",
            "TWVtYmVyT25saW5lRGF0YUgAiAEBQg4KDF9vbmxpbmVfZGF0YSJ/ChVQYXJ0",
            "eU1lbWJlck9ubGluZURhdGESEQoJZW50aXR5X2lkGAEgASgGEhEKCWFyZWFf",
            "bmFtZRgCIAEoCRIcCghwb3NpdGlvbhgDIAEoCzIKLmJuZXQuVmVjMxISCgpo",
            "cF9jdXJyZW50GAQgASgNEg4KBmhwX21heBgFIAEoDUIrChVuZXQuYmVzdGlh",
            "LmJuZXQucHJvdG9CElBhcnR5SW5mb1Ntc2dQcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Bnet.Vec3Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Bnet.PartyInfoSMSG), global::Bnet.PartyInfoSMSG.Parser, new[]{ "PartyId", "PartyName", "Member" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bnet.PartyMember), global::Bnet.PartyMember.Parser, new[]{ "MasterName", "OnlineData" }, new[]{ "OnlineData" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bnet.PartyMemberOnlineData), global::Bnet.PartyMemberOnlineData.Parser, new[]{ "EntityId", "AreaName", "Position", "HpCurrent", "HpMax" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// The full party roster, sent to a member whenever the party or one of its members' online state
  /// changes (creation, join, leave, kick). Offline members are included without online_data so the
  /// client can still list them.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PartyInfoSMSG : pb::IMessage<PartyInfoSMSG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PartyInfoSMSG> _parser = new pb::MessageParser<PartyInfoSMSG>(() => new PartyInfoSMSG());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PartyInfoSMSG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bnet.PartyInfoSmsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PartyInfoSMSG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PartyInfoSMSG(PartyInfoSMSG other) : this() {
      partyId_ = other.partyId_;
      partyName_ = other.partyName_;
      member_ = other.member_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PartyInfoSMSG Clone() {
      return new PartyInfoSMSG(this);
    }

    /// <summary>Field number for the "party_id" field.</summary>
    public const int PartyIdFieldNumber = 1;
    private ulong partyId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong PartyId {
      get { return partyId_; }
      set {
        partyId_ = value;
      }
    }

    /// <summary>Field number for the "party_name" field.</summary>
    public const int PartyNameFieldNumber = 2;
    private string partyName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PartyName {
      get { return partyName_; }
      set {
        partyName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "member" field.</summary>
    public const int MemberFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Bnet.PartyMember> _repeated_member_codec
        = pb::FieldCodec.ForMessage(26, global::Bnet.PartyMember.Parser);
    private readonly pbc::RepeatedField<global::Bnet.PartyMember> member_ = new pbc::RepeatedField<global::Bnet.PartyMember>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Bnet.PartyMember> Member {
      get { return member_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PartyInfoSMSG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PartyInfoSMSG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PartyId != other.PartyId) return false;
      if (PartyName != other.PartyName) return false;
      if(!member_.Equals(other.member_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PartyId != 0UL) hash ^= PartyId.GetHashCode();
      if (PartyName.Length != 0) hash ^= PartyName.GetHashCode();
      hash ^= member_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PartyId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(PartyId);
      }
      if (PartyName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PartyName);
      }
      member_.WriteTo(output, _repeated_member_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PartyId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(PartyId);
      }
      if (PartyName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PartyName);
      }
      member_.WriteTo(ref output, _repeated_member_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PartyId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PartyId);
      }
      if (PartyName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PartyName);
      }
      size += member_.CalculateSize(_repeated_member_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PartyInfoSMSG other) {
      if (other == null) {
        return;
      }
      if (other.PartyId != 0UL) {
        PartyId = other.PartyId;
      }
      if (other.PartyName.Length != 0) {
        PartyName = other.PartyName;
      }
      member_.Add(other.member_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PartyId = input.ReadUInt64();
            break;
          }
          case 18: {
            PartyName = input.ReadString();
            break;
          }
          case 26: {
            member_.AddEntriesFrom(input, _repeated_member_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PartyId = input.ReadUInt64();
            break;
          }
          case 18: {
            PartyName = input.ReadString();
            break;
          }
          case 26: {
            member_.AddEntriesFrom(ref input, _repeated_member_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PartyMember : pb::IMessage<PartyMember>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PartyMember> _parser = new pb::MessageParser<PartyMember>(() => new PartyMember());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PartyMember> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bnet.PartyInfoSmsgReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PartyMember() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PartyMember(PartyMember other) : this() {
      masterName_ = other.masterName_;
      onlineData_ = other.onlineData_ != null ? other.onlineData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PartyMember Clone() {
      return new PartyMember(this);
    }

    /// <summary>Field number for the "master_name" field.</summary>
    public const int MasterNameFieldNumber = 1;
    private string masterName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MasterName {
      get { return masterName_; }
      set {
        masterName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "online_data" field.</summary>
    public const int OnlineDataFieldNumber = 2;
    private global::Bnet.PartyMemberOnlineData onlineData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bnet.PartyMemberOnlineData OnlineData {
      get { return onlineData_; }
      set {
        onlineData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PartyMember);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PartyMember other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MasterName != other.MasterName) return false;
      if (!object.Equals(OnlineData, other.OnlineData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MasterName.Length != 0) hash ^= MasterName.GetHashCode();
      if (onlineData_ != null) hash ^= OnlineData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MasterName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MasterName);
      }
      if (onlineData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OnlineData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MasterName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MasterName);
      }
      if (onlineData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OnlineData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MasterName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MasterName);
      }
      if (onlineData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OnlineData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PartyMember other) {
      if (other == null) {
        return;
      }
      if (other.MasterName.Length != 0) {
        MasterName = other.MasterName;
      }
      if (other.onlineData_ != null) {
        if (onlineData_ == null) {
          OnlineData = new global::Bnet.PartyMemberOnlineData();
        }
        OnlineData.MergeFrom(other.OnlineData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MasterName = input.ReadString();
            break;
          }
          case 18: {
            if (onlineData_ == null) {
              OnlineData = new global::Bnet.PartyMemberOnlineData();
            }
            input.ReadMessage(OnlineData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MasterName = input.ReadString();
            break;
          }
          case 18: {
            if (onlineData_ == null) {
              OnlineData = new global::Bnet.PartyMemberOnlineData();
            }
            input.ReadMessage(OnlineData);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PartyMemberOnlineData : pb::IMessage<PartyMemberOnlineData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PartyMemberOnlineData> _parser = new pb::MessageParser<PartyMemberOnlineData>(() => new PartyMemberOnlineData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PartyMemberOnlineData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bnet.PartyInfoSmsgReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PartyMemberOnlineData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PartyMemberOnlineData(PartyMemberOnlineData other) : this() {
      entityId_ = other.entityId_;
      areaName_ = other.areaName_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      hpCurrent_ = other.hpCurrent_;
      hpMax_ = other.hpMax_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PartyMemberOnlineData Clone() {
      return new PartyMemberOnlineData(this);
    }

    /// <summary>Field number for the "entity_id" field.</summary>
    public const int EntityIdFieldNumber = 1;
    private ulong entityId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong EntityId {
      get { return entityId_; }
      set {
        entityId_ = value;
      }
    }

    /// <summary>Field number for the "area_name" field.</summary>
    public const int AreaNameFieldNumber = 2;
    private string areaName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AreaName {
      get { return areaName_; }
      set {
        areaName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 3;
    private global::Bnet.Vec3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bnet.Vec3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "hp_current" field.</summary>
    public const int HpCurrentFieldNumber = 4;
    private uint hpCurrent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint HpCurrent {
      get { return hpCurrent_; }
      set {
        hpCurrent_ = value;
      }
    }

    /// <summary>Field number for the "hp_max" field.</summary>
    public const int HpMaxFieldNumber = 5;
    private uint hpMax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint HpMax {
      get { return hpMax_; }
      set {
        hpMax_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PartyMemberOnlineData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PartyMemberOnlineData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EntityId != other.EntityId) return false;
      if (AreaName != other.AreaName) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (HpCurrent != other.HpCurrent) return false;
      if (HpMax != other.HpMax) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EntityId != 0UL) hash ^= EntityId.GetHashCode();
      if (AreaName.Length != 0) hash ^= AreaName.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (HpCurrent != 0) hash ^= HpCurrent.GetHashCode();
      if (HpMax != 0) hash ^= HpMax.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EntityId != 0UL) {
        output.WriteRawTag(9);
        output.WriteFixed64(EntityId);
      }
      if (AreaName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AreaName);
      }
      if (position_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (HpCurrent != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(HpCurrent);
      }
      if (HpMax != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(HpMax);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EntityId != 0UL) {
        output.WriteRawTag(9);
        output.WriteFixed64(EntityId);
      }
      if (AreaName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AreaName);
      }
      if (position_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (HpCurrent != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(HpCurrent);
      }
      if (HpMax != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(HpMax);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EntityId != 0UL) {
        size += 1 + 8;
      }
      if (AreaName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AreaName);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (HpCurrent != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HpCurrent);
      }
      if (HpMax != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HpMax);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PartyMemberOnlineData other) {
      if (other == null) {
        return;
      }
      if (other.EntityId != 0UL) {
        EntityId = other.EntityId;
      }
      if (other.AreaName.Length != 0) {
        AreaName = other.AreaName;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Bnet.Vec3();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.HpCurrent != 0) {
        HpCurrent = other.HpCurrent;
      }
      if (other.HpMax != 0) {
        HpMax = other.HpMax;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            EntityId = input.ReadFixed64();
            break;
          }
          case 18: {
            AreaName = input.ReadString();
            break;
          }
          case 26: {
            if (position_ == null) {
              Position = new global::Bnet.Vec3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 32: {
            HpCurrent = input.ReadUInt32();
            break;
          }
          case 40: {
            HpMax = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            EntityId = input.ReadFixed64();
            break;
          }
          case 18: {
            AreaName = input.ReadString();
            break;
          }
          case 26: {
            if (position_ == null) {
              Position = new global::Bnet.Vec3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 32: {
            HpCurrent = input.ReadUInt32();
            break;
          }
          case 40: {
            HpMax = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
