// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages/party/party_invitation_smsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bnet {

  /// <summary>Holder for reflection information generated from messages/party/party_invitation_smsg.proto</summary>
  public static partial class PartyInvitationSmsgReflection {

    #region Descriptor
    /// <summary>File descriptor for messages/party/party_invitation_smsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PartyInvitationSmsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiptZXNzYWdlcy9wYXJ0eS9wYXJ0eV9pbnZpdGF0aW9uX3Ntc2cucHJvdG8S",
            "BGJuZXQibQoTUGFydHlJbnZpdGF0aW9uU01TRxIZChFpbnZpdGVkX2J5X21h",
            "c3RlchgBIAEoCRIQCghwYXJ0eV9pZBgCIAEoBBISCgpwYXJ0eV9uYW1lGAMg",
            "ASgJEhUKDWludml0YXRpb25faWQYBCABKARCMQoVbmV0LmJlc3RpYS5ibmV0",
            "LnByb3RvQhhQYXJ0eUludml0YXRpb25TbXNnUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Bnet.PartyInvitationSMSG), global::Bnet.PartyInvitationSMSG.Parser, new[]{ "InvitedByMaster", "PartyId", "PartyName", "InvitationId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// The join-request prompt: sent to the invited player, asking whether they want to join the
  /// inviting master's party. Answered with AcceptPartyInviteCMSG / DeclinePartyInviteCMSG, both
  /// referencing invitation_id.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PartyInvitationSMSG : pb::IMessage<PartyInvitationSMSG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PartyInvitationSMSG> _parser = new pb::MessageParser<PartyInvitationSMSG>(() => new PartyInvitationSMSG());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PartyInvitationSMSG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bnet.PartyInvitationSmsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PartyInvitationSMSG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PartyInvitationSMSG(PartyInvitationSMSG other) : this() {
      invitedByMaster_ = other.invitedByMaster_;
      partyId_ = other.partyId_;
      partyName_ = other.partyName_;
      invitationId_ = other.invitationId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PartyInvitationSMSG Clone() {
      return new PartyInvitationSMSG(this);
    }

    /// <summary>Field number for the "invited_by_master" field.</summary>
    public const int InvitedByMasterFieldNumber = 1;
    private string invitedByMaster_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string InvitedByMaster {
      get { return invitedByMaster_; }
      set {
        invitedByMaster_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "party_id" field.</summary>
    public const int PartyIdFieldNumber = 2;
    private ulong partyId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong PartyId {
      get { return partyId_; }
      set {
        partyId_ = value;
      }
    }

    /// <summary>Field number for the "party_name" field.</summary>
    public const int PartyNameFieldNumber = 3;
    private string partyName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PartyName {
      get { return partyName_; }
      set {
        partyName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "invitation_id" field.</summary>
    public const int InvitationIdFieldNumber = 4;
    private ulong invitationId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong InvitationId {
      get { return invitationId_; }
      set {
        invitationId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PartyInvitationSMSG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PartyInvitationSMSG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InvitedByMaster != other.InvitedByMaster) return false;
      if (PartyId != other.PartyId) return false;
      if (PartyName != other.PartyName) return false;
      if (InvitationId != other.InvitationId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (InvitedByMaster.Length != 0) hash ^= InvitedByMaster.GetHashCode();
      if (PartyId != 0UL) hash ^= PartyId.GetHashCode();
      if (PartyName.Length != 0) hash ^= PartyName.GetHashCode();
      if (InvitationId != 0UL) hash ^= InvitationId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (InvitedByMaster.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(InvitedByMaster);
      }
      if (PartyId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(PartyId);
      }
      if (PartyName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PartyName);
      }
      if (InvitationId != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(InvitationId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (InvitedByMaster.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(InvitedByMaster);
      }
      if (PartyId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(PartyId);
      }
      if (PartyName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PartyName);
      }
      if (InvitationId != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(InvitationId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (InvitedByMaster.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InvitedByMaster);
      }
      if (PartyId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PartyId);
      }
      if (PartyName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PartyName);
      }
      if (InvitationId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(InvitationId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PartyInvitationSMSG other) {
      if (other == null) {
        return;
      }
      if (other.InvitedByMaster.Length != 0) {
        InvitedByMaster = other.InvitedByMaster;
      }
      if (other.PartyId != 0UL) {
        PartyId = other.PartyId;
      }
      if (other.PartyName.Length != 0) {
        PartyName = other.PartyName;
      }
      if (other.InvitationId != 0UL) {
        InvitationId = other.InvitationId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            InvitedByMaster = input.ReadString();
            break;
          }
          case 16: {
            PartyId = input.ReadUInt64();
            break;
          }
          case 26: {
            PartyName = input.ReadString();
            break;
          }
          case 32: {
            InvitationId = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            InvitedByMaster = input.ReadString();
            break;
          }
          case 16: {
            PartyId = input.ReadUInt64();
            break;
          }
          case 26: {
            PartyName = input.ReadString();
            break;
          }
          case 32: {
            InvitationId = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
