// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages/shop/shop_offer_smsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bnet {

  /// <summary>Holder for reflection information generated from messages/shop/shop_offer_smsg.proto</summary>
  public static partial class ShopOfferSmsgReflection {

    #region Descriptor
    /// <summary>File descriptor for messages/shop/shop_offer_smsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ShopOfferSmsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNtZXNzYWdlcy9zaG9wL3Nob3Bfb2ZmZXJfc21zZy5wcm90bxIEYm5ldCJh",
            "Cg1TaG9wT2ZmZXJTTVNHEhIKCnNldHRsZW1lbnQYASABKAUSIAoHZW50cmll",
            "cxgCIAMoCzIPLmJuZXQuU2hvcEVudHJ5EhoKEm1lcmNoYW50X2VudGl0eV9p",
            "ZBgDIAEoBCJUCglTaG9wRW50cnkSDwoHaXRlbV9pZBgBIAEoBBIPCgdvZmZl",
            "cmVkGAIgASgFEhEKCWJ1eV9wcmljZRgDIAEoAxISCgpzZWxsX3ByaWNlGAQg",
            "ASgDQisKFW5ldC5iZXN0aWEuYm5ldC5wcm90b0ISU2hvcE9mZmVyU21zZ1By",
            "b3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Bnet.ShopOfferSMSG), global::Bnet.ShopOfferSMSG.Parser, new[]{ "Settlement", "Entries", "MerchantEntityId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bnet.ShopEntry), global::Bnet.ShopEntry.Parser, new[]{ "ItemId", "Offered", "BuyPrice", "SellPrice" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// What one settlement will trade right now, and at what price.
  ///
  /// A snapshot for drawing a window, never a contract: every trade is settled unit by unit against the live
  /// price at the moment it is resolved, so a client acting on a stale window pays the current price rather
  /// than the one it was shown. Re-sent after every trade, which is how the window stays honest.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ShopOfferSMSG : pb::IMessage<ShopOfferSMSG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ShopOfferSMSG> _parser = new pb::MessageParser<ShopOfferSMSG>(() => new ShopOfferSMSG());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ShopOfferSMSG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bnet.ShopOfferSmsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShopOfferSMSG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShopOfferSMSG(ShopOfferSMSG other) : this() {
      settlement_ = other.settlement_;
      entries_ = other.entries_.Clone();
      merchantEntityId_ = other.merchantEntityId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShopOfferSMSG Clone() {
      return new ShopOfferSMSG(this);
    }

    /// <summary>Field number for the "settlement" field.</summary>
    public const int SettlementFieldNumber = 1;
    private int settlement_;
    /// <summary>
    /// Dense settlement index, so a client can tell one town's window from another's.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Settlement {
      get { return settlement_; }
      set {
        settlement_ = value;
      }
    }

    /// <summary>Field number for the "entries" field.</summary>
    public const int EntriesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Bnet.ShopEntry> _repeated_entries_codec
        = pb::FieldCodec.ForMessage(18, global::Bnet.ShopEntry.Parser);
    private readonly pbc::RepeatedField<global::Bnet.ShopEntry> entries_ = new pbc::RepeatedField<global::Bnet.ShopEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Bnet.ShopEntry> Entries {
      get { return entries_; }
    }

    /// <summary>Field number for the "merchant_entity_id" field.</summary>
    public const int MerchantEntityIdFieldNumber = 3;
    private ulong merchantEntityId_;
    /// <summary>
    /// Whose counter this is. Carried rather than remembered by the client, because the window is not always
    /// something the client asked for - asking a merchant for their wares in conversation pushes one.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong MerchantEntityId {
      get { return merchantEntityId_; }
      set {
        merchantEntityId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ShopOfferSMSG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ShopOfferSMSG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Settlement != other.Settlement) return false;
      if(!entries_.Equals(other.entries_)) return false;
      if (MerchantEntityId != other.MerchantEntityId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Settlement != 0) hash ^= Settlement.GetHashCode();
      hash ^= entries_.GetHashCode();
      if (MerchantEntityId != 0UL) hash ^= MerchantEntityId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Settlement != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Settlement);
      }
      entries_.WriteTo(output, _repeated_entries_codec);
      if (MerchantEntityId != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(MerchantEntityId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Settlement != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Settlement);
      }
      entries_.WriteTo(ref output, _repeated_entries_codec);
      if (MerchantEntityId != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(MerchantEntityId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Settlement != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Settlement);
      }
      size += entries_.CalculateSize(_repeated_entries_codec);
      if (MerchantEntityId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MerchantEntityId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ShopOfferSMSG other) {
      if (other == null) {
        return;
      }
      if (other.Settlement != 0) {
        Settlement = other.Settlement;
      }
      entries_.Add(other.entries_);
      if (other.MerchantEntityId != 0UL) {
        MerchantEntityId = other.MerchantEntityId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Settlement = input.ReadInt32();
            break;
          }
          case 18: {
            entries_.AddEntriesFrom(input, _repeated_entries_codec);
            break;
          }
          case 24: {
            MerchantEntityId = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Settlement = input.ReadInt32();
            break;
          }
          case 18: {
            entries_.AddEntriesFrom(ref input, _repeated_entries_codec);
            break;
          }
          case 24: {
            MerchantEntityId = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ShopEntry : pb::IMessage<ShopEntry>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ShopEntry> _parser = new pb::MessageParser<ShopEntry>(() => new ShopEntry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ShopEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bnet.ShopOfferSmsgReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShopEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShopEntry(ShopEntry other) : this() {
      itemId_ = other.itemId_;
      offered_ = other.offered_;
      buyPrice_ = other.buyPrice_;
      sellPrice_ = other.sellPrice_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShopEntry Clone() {
      return new ShopEntry(this);
    }

    /// <summary>Field number for the "item_id" field.</summary>
    public const int ItemIdFieldNumber = 1;
    private ulong itemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ItemId {
      get { return itemId_; }
      set {
        itemId_ = value;
      }
    }

    /// <summary>Field number for the "offered" field.</summary>
    public const int OfferedFieldNumber = 2;
    private int offered_;
    /// <summary>
    /// Units the town will part with: what is on the shelves less what the locals keep back for themselves.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Offered {
      get { return offered_; }
      set {
        offered_ = value;
      }
    }

    /// <summary>Field number for the "buy_price" field.</summary>
    public const int BuyPriceFieldNumber = 3;
    private long buyPrice_;
    /// <summary>
    /// Coins for one unit, buying and selling. The gap between them is the spread, and it is what makes
    /// round-tripping in one town a loss rather than an income.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long BuyPrice {
      get { return buyPrice_; }
      set {
        buyPrice_ = value;
      }
    }

    /// <summary>Field number for the "sell_price" field.</summary>
    public const int SellPriceFieldNumber = 4;
    private long sellPrice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SellPrice {
      get { return sellPrice_; }
      set {
        sellPrice_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ShopEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ShopEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ItemId != other.ItemId) return false;
      if (Offered != other.Offered) return false;
      if (BuyPrice != other.BuyPrice) return false;
      if (SellPrice != other.SellPrice) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ItemId != 0UL) hash ^= ItemId.GetHashCode();
      if (Offered != 0) hash ^= Offered.GetHashCode();
      if (BuyPrice != 0L) hash ^= BuyPrice.GetHashCode();
      if (SellPrice != 0L) hash ^= SellPrice.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ItemId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ItemId);
      }
      if (Offered != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Offered);
      }
      if (BuyPrice != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(BuyPrice);
      }
      if (SellPrice != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(SellPrice);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ItemId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ItemId);
      }
      if (Offered != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Offered);
      }
      if (BuyPrice != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(BuyPrice);
      }
      if (SellPrice != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(SellPrice);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ItemId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ItemId);
      }
      if (Offered != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Offered);
      }
      if (BuyPrice != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(BuyPrice);
      }
      if (SellPrice != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SellPrice);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ShopEntry other) {
      if (other == null) {
        return;
      }
      if (other.ItemId != 0UL) {
        ItemId = other.ItemId;
      }
      if (other.Offered != 0) {
        Offered = other.Offered;
      }
      if (other.BuyPrice != 0L) {
        BuyPrice = other.BuyPrice;
      }
      if (other.SellPrice != 0L) {
        SellPrice = other.SellPrice;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ItemId = input.ReadUInt64();
            break;
          }
          case 16: {
            Offered = input.ReadInt32();
            break;
          }
          case 24: {
            BuyPrice = input.ReadInt64();
            break;
          }
          case 32: {
            SellPrice = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ItemId = input.ReadUInt64();
            break;
          }
          case 16: {
            Offered = input.ReadInt32();
            break;
          }
          case 24: {
            BuyPrice = input.ReadInt64();
            break;
          }
          case 32: {
            SellPrice = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
