// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages/map/world_time_smsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bnet {

  /// <summary>Holder for reflection information generated from messages/map/world_time_smsg.proto</summary>
  public static partial class WorldTimeSmsgReflection {

    #region Descriptor
    /// <summary>File descriptor for messages/map/world_time_smsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WorldTimeSmsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJtZXNzYWdlcy9tYXAvd29ybGRfdGltZV9zbXNnLnByb3RvEgRibmV0IkwK",
            "DVdvcmxkVGltZVNNU0cSIAoYd29ybGRfYWdlX2Jlc3RpYV9zZWNvbmRzGAEg",
            "ASgBEhkKEXRpbWVfc3BlZWRfZmFjdG9yGAIgASgBQisKFW5ldC5iZXN0aWEu",
            "Ym5ldC5wcm90b0ISV29ybGRUaW1lU01TR1Byb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Bnet.WorldTimeSMSG), global::Bnet.WorldTimeSMSG.Parser, new[]{ "WorldAgeBestiaSeconds", "TimeSpeedFactor" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///*
  /// Re-anchors the client's calendar to a reading the server has just changed.
  ///
  /// ### Why this is not simply `WorldInfoSMSG` again
  ///
  /// `WorldInfoSMSG` carries the same two fields, and resending it would set the clock - but it also states the
  /// world's identity and geometry, and a client that receives it treats that as "a new world, or a reconnect"
  /// and drops every chunk it holds. Using it to move a clock would tear the terrain down and stream it back,
  /// which is a very expensive way to say that it is now half past two.
  ///
  /// So: the shape of the calendar stays on `WorldInfoSMSG`, because it is the world's identity and does not
  /// move. Only the reading is here.
  ///
  /// ### Nothing sends this on a timer
  ///
  /// The clock is still an anchor the client runs forward on its own - one message per connection, not one per
  /// second per player. This exists for the case that anchor cannot cover: the server's clock jumping
  /// discontinuously, which today means a GM moving it with `/date`. A client that never receives one of these
  /// is not missing anything.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WorldTimeSMSG : pb::IMessage<WorldTimeSMSG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorldTimeSMSG> _parser = new pb::MessageParser<WorldTimeSMSG>(() => new WorldTimeSMSG());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorldTimeSMSG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bnet.WorldTimeSmsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldTimeSMSG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldTimeSMSG(WorldTimeSMSG other) : this() {
      worldAgeBestiaSeconds_ = other.worldAgeBestiaSeconds_;
      timeSpeedFactor_ = other.timeSpeedFactor_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldTimeSMSG Clone() {
      return new WorldTimeSMSG(this);
    }

    /// <summary>Field number for the "world_age_bestia_seconds" field.</summary>
    public const int WorldAgeBestiaSecondsFieldNumber = 1;
    private double worldAgeBestiaSeconds_;
    /// <summary>
    ///*
    /// Bestia-seconds elapsed since the world began, as of the moment this message was built.
    ///
    /// Elapsed time rather than a wall-clock instant, for the reason `WorldInfoSMSG` sends elapsed time: the
    /// client is never trusted to know what time it is, so a machine with a badly set clock shows the same
    /// in-game date as everyone else.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double WorldAgeBestiaSeconds {
      get { return worldAgeBestiaSeconds_; }
      set {
        worldAgeBestiaSeconds_ = value;
      }
    }

    /// <summary>Field number for the "time_speed_factor" field.</summary>
    public const int TimeSpeedFactorFieldNumber = 2;
    private double timeSpeedFactor_;
    /// <summary>
    ///*
    /// How many times faster Bestia time runs than real time.
    ///
    /// Repeated from `WorldInfoSMSG` so this message is a complete anchor on its own. It is a setting, so it
    /// *can* differ from what the connection was first told - and a re-anchor that set the reading while leaving
    /// the client advancing it at a stale rate would drift instead of failing.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double TimeSpeedFactor {
      get { return timeSpeedFactor_; }
      set {
        timeSpeedFactor_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorldTimeSMSG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorldTimeSMSG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(WorldAgeBestiaSeconds, other.WorldAgeBestiaSeconds)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(TimeSpeedFactor, other.TimeSpeedFactor)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (WorldAgeBestiaSeconds != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(WorldAgeBestiaSeconds);
      if (TimeSpeedFactor != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(TimeSpeedFactor);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (WorldAgeBestiaSeconds != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(WorldAgeBestiaSeconds);
      }
      if (TimeSpeedFactor != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(TimeSpeedFactor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (WorldAgeBestiaSeconds != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(WorldAgeBestiaSeconds);
      }
      if (TimeSpeedFactor != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(TimeSpeedFactor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (WorldAgeBestiaSeconds != 0D) {
        size += 1 + 8;
      }
      if (TimeSpeedFactor != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorldTimeSMSG other) {
      if (other == null) {
        return;
      }
      if (other.WorldAgeBestiaSeconds != 0D) {
        WorldAgeBestiaSeconds = other.WorldAgeBestiaSeconds;
      }
      if (other.TimeSpeedFactor != 0D) {
        TimeSpeedFactor = other.TimeSpeedFactor;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            WorldAgeBestiaSeconds = input.ReadDouble();
            break;
          }
          case 17: {
            TimeSpeedFactor = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            WorldAgeBestiaSeconds = input.ReadDouble();
            break;
          }
          case 17: {
            TimeSpeedFactor = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
