# ===============================
# = LOGGING
# ===============================
logging:
  level:
    ROOT: WARN
    akka.management.cluster: INFO
    # org.neo4j.driver.GraphDatabase: debug
    # org.neo4j.driver.Driver: debug
    net.bestia: DEBUG
    de.tfelix.bestia: DEBUG
    net.bestia.entity.EntityService: INFO
    net.bestia.zoneserver.actor: TRACE
    net.bestia.zoneserver.messages: TRACE

# ===============================
# = LIBRARIES
# ===============================
spring:
  main:
    web-environment: false
    web-application-type: none
  datasource:
    url: jdbc:mysql://192.168.178.220:3306/bestia?serverTimezone=UTC
    username: bestia
    password: bestia
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: false
    # Hibernate ddl auto (create, create-drop, update): with "update" the database
    # schema will be automatically updated accordingly to java entities found in
    # the project
    hibernate:
      ddl-auto: update
    # Allows Hibernate to generate SQL optimized for a particular DBMS
    properties.hibernate.dialect: org.hibernate.dialect.MariaDB53Dialect
  data:
    neo4j:
      uri: bolt://192.168.178.220:7687
      username: neo4j
      password: bestia

flyway:
  enabled: false

# ===============================
# = ZONE
# ===============================
zone:
  # The version property expansion is currently broken with gradle
  version: 1.0.0-ALPHA
  name: zoneserver-${random.uuid}
  node-id: 1
  bind-address: localhost
  port: 8990
  max-connections: 1123
  root-auth-token: 50cb5740-c390-4d48-932f-eef7cbc113c1

mapgen:
  temp-dir: D:/bestia_map
  # Size of the data transfer object which are used to store the map.
  dto-size: 100

script:
  path: classpath:script