# ===============================
# = LOGGING
# ===============================
logging:
  level:
    ROOT: WARN
    akka.management.cluster: INFO
    net.bestia: TRACE
    de.tfelix.bestia: TRACE
    net.bestia.entity.component.StatusService: DEBUG
    net.bestia.entity.component.EntityService: DEBUG
    net.bestia.zoneserver.connection.LatencyService: INFO
    net.bestia.zoneserver.actor.zone.WebIngestActor: INFO
    net.bestia.zoneserver.client.LatencyService: WARN
    net.bestia.zoneserver.actor.zone.ClientMessageActor: WARN
    net.bestia.entity.EntityService: INFO

# ===============================
# = LIBRARIES
# ===============================
spring:
  main:
    web-environment: false
  datasource:
    url: jdbc:mysql://localhost:3306/bestia?serverTimezone=UTC
    username: bestia
    password: bestia
    driver-class-name: com.mysql.cj.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
    # Hibernate ddl auto (create, create-drop, update): with "update" the database
    # schema will be automatically updated accordingly to java entities found in
    # the project
    hibernate.ddl-auto: none
    # Allows Hibernate to generate SQL optimized for a particular DBMS
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = ZONE
# ===============================
server:
  # The version property expansion is currently broken with gradle
  version: 0.5.0-ALPHA
  name: zoneserver-${random.uuid}
  websocketPort: 8990

mapgen:
  tempDir: D:/bestia_map
  # Size of the data transfer object which are used to store the map.
  dtoSize: 100

script:
  path: classpath:script