# ===============================
# = LOGGING
# ===============================
logging:
  level:
    ROOT: WARN
    akka.management.cluster: INFO
    net.bestia: TRACE
    de.tfelix.bestia: TRACE
    net.bestia.entity.EntityService: INFO

# ===============================
# = LIBRARIES
# ===============================
spring:
  main:
    web-environment: false
    web-application-type: none
  datasource:
    url: jdbc:mysql://192.168.178.220:3306/bestia?serverTimezone=UTC
    username: bestia
    password: bestia
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: false
    # Hibernate ddl auto (create, create-drop, update): with "update" the database
    # schema will be automatically updated accordingly to java entities found in
    # the project
    hibernate:
      ddl-auto: validate
    # Allows Hibernate to generate SQL optimized for a particular DBMS
    properties.hibernate.dialect: org.hibernate.dialect.MariaDB53Dialect

# ===============================
# = ZONE
# ===============================
server:
  # The version property expansion is currently broken with gradle
  version: 1.0.0-ALPHA
  name: zoneserver-${random.uuid}
  bind-address: localhost
  port: 8990
  max-connections: 1000
  devAuthToken: b53dc8ce-9702-4aeb-aa60-4ed33f314965

mapgen:
  tempDir: D:/bestia_map
  # Size of the data transfer object which are used to store the map.
  dtoSize: 100

script:
  path: classpath:script