
server:
   name: zoneserver-${random.uuid}
   version: \@project.version\@
   entityBuffer: 100

mapgen:
  tempDir: D:/bestia_map
  # Size of the data transfer object which are used to store the map.
  dtoSize: 100

# The key of the re-captcha authentication checks.
recaptcha:
  secretKey: XXXXXX

logging:
  level:
    ROOT: WARN
    net.bestia: TRACE
    de.tfelix.bestia: TRACE
    net.bestia.entity.component.StatusService: DEBUG
    net.bestia.entity.component.EntityService: DEBUG
    net.bestia.zoneserver.connection.LatencyService: INFO
    net.bestia.zoneserver.actor.zone.WebIngestActor: INFO
    net.bestia.zoneserver.client.LatencyService: WARN
    net.bestia.zoneserver.actor.zone.ClientMessageActor: WARN
    net.bestia.entity.EntityService: INFO

# ===============================
# = SCRIPTS
# ===============================
script:
  path: classpath:script

# ===============================
# = DATA SOURCE
# ===============================

# Set here configurations for the database connection

# Connection url for the database "netgloo_blog"
spring:
  main:
    web-environment: false
  datasource:
    url: jdbc:mysql://localhost/bestia?serverTimezone=UTC
    username: bestia
    password: bestia
    driver-class-name: com.mysql.cj.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
    # Hibernate ddl auto (create, create-drop, update): with "update" the database
    # schema will be automatically updated accordingly to java entities found in
    # the project
    hibernate.ddl-auto: update
    # Allows Hibernate to generate SQL optimized for a particular DBMS
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect