package net.bestia.worldgen.render

import net.bestia.worldgen.vector.PointMarker

/**
 * A marker attribute the caller is willing not to find.
 *
 * [PointMarker.attribute] throws on a missing channel, and rightly so - a stage asking for an attribute its
 * own markers do not carry is a construction bug. A renderer is the caller for which it is not: it draws
 * whatever a world happens to contain, and a world generated by a pipeline without the history or economy
 * stages has settlement markers with fewer channels on them. Asking and accepting no is the correct shape
 * here, and it is better than a `runCatching` around a `require`.
 *
 * Public rather than `internal` because zone-server's map tiles ask the same question of the same markers, and
 * `internal` is module-scoped.
 */
fun PointMarker.optionalAttribute(name: String): Double? {
  val table = attributes ?: return null
  val channel = table.channelNames.indexOf(name)
  return if (channel < 0) null else table.valueAt(channel, 0)
}
