# ===============================
# = General server
# ===============================
server:
  name: webserver-${random.uuid}
  maxDeadLetters: 10
  port: 8090


logging:
  level:
    net.bestia: DEBUG

# Exclude database config detected by model import.
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
