package net.bestia.messages;

// TODO kommentiern.
public class InputWrapperMessage<T extends Message> extends InputMessage {

	private static final long serialVersionUID = 1L;

	private static final String MESSAGE_ID = "inputwrapper";
	
	private final T message;
	
	public InputWrapperMessage() {
		message = null;
	}

	public InputWrapperMessage(T msg, int playerBestiaId) {
		super(msg, playerBestiaId);

		this.message = msg;
	}
	
	/**
	 * Returns the message ID the wrapped message will return. By using this
	 * method we can check for message IDs which will get returned by this
	 * wrapper message. Useful if our command from the command factory should
	 * trigger only for this wrapped messages.
	 * 
	 * @param originalMessageId
	 * @return Wrapped message ID generated by this wrapped message.
	 */
	public static String getWrappedMessageId(String originalMessageId) {
		return String.format("%s-%s", MESSAGE_ID, originalMessageId);
	}
	
	@Override
	public String getMessageId() {
		return (message == null) ? MESSAGE_ID : String.format("%s-%s", MESSAGE_ID, message.getMessageId());
	}

	@Override
	public String getMessagePath() {
		return getZoneMessagePath();
	}

	/**
	 * Returns the wrapped chat message.
	 * 
	 * @return The wrapped chat message.
	 */
	public T getMessage() {
		return message;
	}

}
