package net.bestia.zone.world.stream

import net.bestia.zone.ecs.movement.GroundHeight
import org.springframework.stereotype.Service

/**
 * Answers [GroundHeight] from the generated heightfield.
 *
 * Deliberately thin: the whole point of the interface is that `ecs/movement` does not depend on the streaming
 * layer, so all the knowledge about voxel sizes, sea level and the position-unit convention stays on this side
 * of it. See [ChunkCoords.standingZ] for the conversion and why it rounds.
 *
 * Reads the *base* terrain, so it does not see player edits - a player who digs a pit does not fall into it.
 * `ChunkService.derived()` is the edit-aware answer and is the right source once anything can dig; it costs a
 * chunk materialisation rather than a raster sample, which is why it is not used for every step yet.
 */
@Service
class ChunkGroundHeight(private val chunkService: ChunkService) : GroundHeight {

  override fun standingZAt(x: Long, y: Long): Long? {
    // The world is generated by the first boot runner and the tick loop is a boot runner too, so there is a
    // window where movement can run before there is any terrain to stand on.
    if (!chunkService.isReady) return null

    val ground = chunkService.surfaceElevationAt(x, y) ?: return null

    return ChunkCoords.standingZ(chunkService.config, ground)
  }
}
