version: '3'
services:
  mysql:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bestia
      MYSQL_USER: bestia
      MYSQL_PASSWORD: bestia
      MYSQL_ROOT_PASSWORD: bestia
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: bestia
      MONGO_INITDB_ROOT_PASSWORD: bestia
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: bestia
      ME_CONFIG_MONGODB_ADMINPASSWORD: bestia