package net.bestia.worldgen.civ

import net.bestia.worldgen.core.MovementMode
import net.bestia.worldgen.core.NavEdgeKind
import net.bestia.worldgen.core.NavNodeKind
import net.bestia.worldgen.core.WorldConfig
import net.bestia.worldgen.pipeline.StandardWorld
import net.bestia.worldgen.vector.FeatureKind
import net.bestia.worldgen.vector.PointMarker
import net.bestia.worldgen.vector.Vec2d
import kotlin.math.tan
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

class NavGraphStageTest {

  /**
   * The same size `StandardWorldTest` uses, and for the same reason: small enough to generate quickly,
   * large enough that the civilisation stages actually place roads and towns to read.
   */
  private fun config(seed: Long) = WorldConfig(
    seed = seed,
    widthCells = 160,
    heightCells = 160,
    chunkSize = 32,
    voxelSize = 1.0
  )

  private val generated by lazy { StandardWorld.build(config(0xC0FFEEL)) }
  private val graph by lazy { generated.world.navGraph }

  @Test
  fun `the world has a navigation graph with both settlements and open country in it`() {
    assertTrue(graph.nodes.isNotEmpty(), "no navigation nodes at all")
    assertTrue(graph.edges.isNotEmpty(), "no navigation edges at all")

    val byKind = graph.nodes.groupingBy { it.kind }.eachCount()

    // Both halves of the design have to be present, and the failure modes are different: no settlement
    // nodes means the feature read is broken, no wilderness nodes means the lattice is - and a graph with
    // only one of the two would still look plausible in a count.
    assertTrue((byKind[NavNodeKind.SETTLEMENT] ?: 0) > 0, "no settlement nodes: $byKind")
    assertTrue((byKind[NavNodeKind.WILDERNESS] ?: 0) > 0, "no wilderness nodes: $byKind")
  }

  @Test
  fun `every node carries a settlement index exactly when it belongs to a settlement`() {
    for (node in graph.nodes) {
      when (node.kind) {
        NavNodeKind.SETTLEMENT, NavNodeKind.GATE ->
          assertTrue(node.settlementIndex >= 0, "$node belongs to a settlement but carries no index")

        NavNodeKind.WILDERNESS, NavNodeKind.BRIDGE_APPROACH, NavNodeKind.CAVE_ENTRANCE ->
          assertEquals(-1, node.settlementIndex, "$node belongs to no settlement but carries an index")
      }
    }
  }

  @Test
  fun `settlement nodes agree with the settlement features they came from`() {
    val settlements = generated.world.features.all()
      .filter { it.kind == FeatureKind.SETTLEMENT }
      .filterIsInstance<PointMarker>()
      .associateBy { it.attribute(SettlementChannels.INDEX).toInt() }

    val nodes = graph.nodes.filter { it.kind == NavNodeKind.SETTLEMENT }

    assertEquals(settlements.size, nodes.size, "one node per settlement, no more and no fewer")

    for (node in nodes) {
      val marker = assertNotNull(
        settlements[node.settlementIndex],
        "node ${node.id} claims settlement ${node.settlementIndex}, which is not a settlement"
      )
      assertEquals(marker.position, node.position, "node ${node.id} is not where its settlement is")
    }
  }

  @Test
  fun `no edge is generated over ground steeper than the slope cutoff`() {
    // The requirement, checked where the stage can actually see it. Wilderness edges are the ones this
    // stage routes itself and therefore the ones it is responsible for - a road was graded by whoever built
    // it, and the sub-kilometre cliff neither this test nor the stage can see is the chunk tier's business.
    val params = NavParams()
    val limit = tan(Math.toRadians(params.maxSlopeDegrees))

    val elevation = generated.world.layers
      .require<net.bestia.worldgen.core.FloatLayer>(net.bestia.worldgen.core.LayerId.ELEVATION)
    val metres = elevation.region.resolution.metresPerCell

    var checked = 0
    for (edge in graph.edges) {
      if (edge.kind != NavEdgeKind.WILDERNESS) continue

      val points = buildList {
        add(graph.nodes[edge.a.value].position)
        edge.waypoints?.let { addAll(it) }
        add(graph.nodes[edge.b.value].position)
      }

      for (i in 1 until points.size) {
        val from = points[i - 1]
        val to = points[i]
        val run = from.distanceTo(to)
        if (run < metres * 0.5) continue

        val rise = kotlin.math.abs(elevationAt(elevation, to) - elevationAt(elevation, from))
        val slope = rise / run

        // A tolerance, because the stage gates on cell-to-cell steps and this walks the waypoints it
        // emitted - the same ground sampled at a slightly different spacing.
        assertTrue(
          slope <= limit * 1.5,
          "wilderness edge $edge climbs at $slope between $from and $to, over the ${limit} cutoff"
        )
        checked++
      }
    }

    assertTrue(checked > 0, "no wilderness edge segments were testable")
  }

  @Test
  fun `modes are requirements, so a made surface demands nothing but walking`() {
    for (edge in graph.edges) {
      assertTrue(edge.modes.isNotEmpty(), "$edge is untraversable and should not exist")

      when (edge.kind) {
        // The edge a land animal has to be refused. If WALK ever leaks onto a lane, "cannot swim" stops
        // meaning anything and merchants start marching across the ocean.
        NavEdgeKind.SEA_LANE ->
          assertEquals(setOf(MovementMode.SWIM), edge.modes, "$edge is a shipping lane that can be walked")

        // A graded surface demands no special capability of anyone - that it is *faster* is what
        // NavEdgeKind carries. A road that demanded CLIMB or SWIM would be a road nothing could use.
        NavEdgeKind.ROAD, NavEdgeKind.BRIDGE, NavEdgeKind.GATE_SPOKE ->
          assertEquals(setOf(MovementMode.WALK), edge.modes, "$edge is a made surface with extra demands")

        // Open country is whatever the ground turned out to be.
        NavEdgeKind.WILDERNESS ->
          assertTrue(MovementMode.WALK in edge.modes || MovementMode.SWIM in edge.modes, "$edge has no way across")
      }
    }
  }

  @Test
  fun `a creature that cannot swim is refused every edge that fords water`() {
    // The requirement, expressed the way a consumer will read it: modes are a conjunction, so filtering by
    // "has every mode this edge demands" has to exclude a stream crossing from a non-swimmer. Under an
    // any-of reading these edges would pass on WALK alone, which is the bug this asserts against.
    val landlocked = setOf(MovementMode.WALK, MovementMode.CLIMB)
    val fords = graph.edges.filter { MovementMode.SWIM in it.modes }

    assertTrue(fords.isNotEmpty(), "no edge in this world crosses water, so the rule is untested")

    for (ford in fords) {
      assertTrue(
        !landlocked.containsAll(ford.modes),
        "$ford would be offered to a creature that cannot swim"
      )
    }
  }

  @Test
  fun `bridges carry a width limit and roads do not`() {
    val bridges = graph.edges.filter { it.kind == NavEdgeKind.BRIDGE }

    for (bridge in bridges) {
      assertTrue(
        bridge.maxAgentHalfWidth < Double.MAX_VALUE && bridge.maxAgentHalfWidth > 0.0,
        "$bridge has no width limit, so nothing can ever be too big for it"
      )
    }

    for (road in graph.edges.filter { it.kind == NavEdgeKind.ROAD }) {
      assertEquals(
        Double.MAX_VALUE,
        road.maxAgentHalfWidth,
        "$road constrains width; only a crossing should"
      )
    }
  }

  @Test
  fun `a made surface is cheaper per metre than open country`() {
    // The "high speed, low cost network" the whole design turns on. Asserted as an average rather than
    // per edge, because a wilderness hop over a meadow can legitimately be as cheap as a road.
    val roads = graph.edges.filter { it.kind == NavEdgeKind.ROAD && it.lengthMetres > 0.0 }
    val wild = graph.edges.filter { it.kind == NavEdgeKind.WILDERNESS && it.lengthMetres > 0.0 }

    if (roads.isEmpty() || wild.isEmpty()) return

    val roadCost = roads.sumOf { it.baseCost } / roads.sumOf { it.lengthMetres }
    val wildCost = wild.sumOf { it.baseCost } / wild.sumOf { it.lengthMetres }

    assertTrue(
      roadCost < wildCost,
      "a road costs $roadCost per metre and open country $wildCost - roads are supposed to be the fast way"
    )
  }

  @Test
  fun `the graph is reproducible from the seed`() {
    // Node ids are how a runtime's blocked-edge overlay survives a restart, so two runs of the same seed
    // producing different ids would silently re-point every override at a different bridge.
    val once = StandardWorld.build(config(31337L)).world.navGraph
    val twice = StandardWorld.build(config(31337L)).world.navGraph

    assertEquals(once.nodes.size, twice.nodes.size)
    assertEquals(once.edges.size, twice.edges.size)

    for (i in once.nodes.indices) {
      assertEquals(once.nodes[i].position, twice.nodes[i].position, "node $i moved between runs")
      assertEquals(once.nodes[i].kind, twice.nodes[i].kind, "node $i changed kind between runs")
    }
    for (i in once.edges.indices) {
      assertEquals(once.edges[i].a, twice.edges[i].a, "edge $i changed endpoint between runs")
      assertEquals(once.edges[i].b, twice.edges[i].b, "edge $i changed endpoint between runs")
      assertEquals(once.edges[i].modes, twice.edges[i].modes, "edge $i changed modes between runs")
    }
  }

  @Test
  fun `nearestNode finds a node from a position and respects its limit`() {
    val target = graph.nodes[graph.nodes.size / 2]

    assertEquals(target.id, graph.nearestNode(target.position)?.id, "a node is not nearest to itself")

    // Bounded queries take a different path through the bucket index than unbounded ones, so both need
    // exercising - and the bound has to actually exclude, or an NPC would snap to the graph from anywhere.
    assertEquals(target.id, graph.nearestNode(target.position, maxDistance = 1.0)?.id)

    val faraway = Vec2d(-1_000_000.0, -1_000_000.0)
    assertNull(graph.nearestNode(faraway, maxDistance = 100.0), "a node turned up a thousand km away")
    assertNotNull(graph.nearestNode(faraway), "an unbounded query found nothing at all")
  }

  @Test
  fun `every edge connects two distinct nodes that exist`() {
    // The graph's own constructor checks this, so a clean build is most of the assertion. What is added
    // here is that the incidence index agrees with the edge list, since the two are built separately.
    for ((index, edge) in graph.edges.withIndex()) {
      assertTrue(index in graph.incidentEdges[edge.a.value].toList(), "$edge is missing from ${edge.a}")
      assertTrue(index in graph.incidentEdges[edge.b.value].toList(), "$edge is missing from ${edge.b}")
    }
  }

  @Test
  fun `most of the graph is reachable from its largest settlement`() {
    // A graph in a hundred disconnected pieces would satisfy every other test here and be useless: an NPC
    // could plan a journey only inside whatever fragment it happened to spawn in. Islands are legitimate -
    // this world has sea - so the bar is a large majority rather than everything.
    val start = graph.nodes.firstOrNull { it.kind == NavNodeKind.SETTLEMENT } ?: return

    val seen = BooleanArray(graph.nodes.size)
    val pending = ArrayDeque<Int>()
    seen[start.id.value] = true
    pending.add(start.id.value)

    while (pending.isNotEmpty()) {
      val at = pending.removeFirst()
      for (edgeIndex in graph.incidentEdges[at]) {
        val next = graph.edges[edgeIndex].other(net.bestia.worldgen.core.NavNodeId(at)).value
        if (seen[next]) continue
        seen[next] = true
        pending.add(next)
      }
    }

    val reached = seen.count { it }.toDouble() / graph.nodes.size
    assertTrue(reached > 0.5, "only ${(reached * 100).toInt()}% of the graph is reachable from a town")
  }

  private fun elevationAt(
    layer: net.bestia.worldgen.core.FloatLayer,
    position: Vec2d
  ): Double {
    val metres = layer.region.resolution.metresPerCell
    val x = Math.floor(position.x / metres).toInt().coerceIn(layer.region.minX, layer.region.maxX)
    val y = Math.floor(position.y / metres).toInt().coerceIn(layer.region.minY, layer.region.maxY)
    return layer[x, y].toDouble()
  }
}
